import { WorldLot } from './types';

export const INITIAL_NEIGHBORHOOD_LOTS: Record<string, WorldLot> = {
  lot_home: {
    id: 'lot_home',
    type: 'home',
    name: 'Player Household',
    width: 20,
    height: 20,
    blockedCells: [],
    walls: [
      { id: 'w1', x1: 0, y1: 0, x2: 20, y2: 0, provenance: 'earned' },
      { id: 'w2', x1: 20, y1: 0, x2: 20, y2: 20, provenance: 'earned' },
      { id: 'w3', x1: 20, y1: 20, x2: 0, y2: 20, provenance: 'earned' },
      { id: 'w4', x1: 0, y1: 20, x2: 0, y2: 0, provenance: 'earned' },
    ],
    doors: [{ id: 'd1', x: 10, y: 20, orientation: 'horizontal', provenance: 'earned' }],
    objects: [
      {
        id: 'obj_bed_1',
        catalogId: 'cozy_cat_bed',
        name: 'Cozy Cat Bed',
        category: 'sleep',
        x: 3,
        y: 3,
        width: 2,
        height: 2,
        interactSpots: [{ x: 4, y: 3 }],
        provenance: 'earned',
      },
      {
        id: 'obj_bowl_1',
        catalogId: 'food_bowl',
        name: 'Stainless Food Bowl',
        category: 'care',
        x: 6,
        y: 2,
        width: 1,
        height: 1,
        interactSpots: [{ x: 6, y: 3 }],
        provenance: 'earned',
      },
      {
        id: 'obj_tree_1',
        catalogId: 'scratch_post',
        name: 'Tall Cat Tree',
        category: 'play',
        x: 15,
        y: 5,
        width: 2,
        height: 2,
        interactSpots: [{ x: 15, y: 7 }],
        provenance: 'earned',
      },
    ],
  },
  npc_home_1: {
    id: 'npc_home_1',
    type: 'npc_home',
    name: 'Maple Cottage',
    width: 16,
    height: 16,
    blockedCells: [],
    walls: [
      { id: 'w1', x1: 0, y1: 0, x2: 16, y2: 0, provenance: 'earned' },
      { id: 'w2', x1: 16, y1: 0, x2: 16, y2: 16, provenance: 'earned' },
      { id: 'w3', x1: 16, y1: 16, x2: 0, y2: 16, provenance: 'earned' },
      { id: 'w4', x1: 0, y1: 16, x2: 0, y2: 0, provenance: 'earned' },
    ],
    doors: [{ id: 'd1', x: 8, y: 16, orientation: 'horizontal', provenance: 'earned' }],
    objects: [
      {
        id: 'npc1_sofa',
        catalogId: 'comfy_sofa',
        name: 'Plush Lounge Sofa',
        category: 'seating',
        x: 4,
        y: 4,
        width: 3,
        height: 2,
        interactSpots: [{ x: 5, y: 6 }],
        provenance: 'earned',
      },
    ],
    residentCatIds: ['npc_cat_barnaby', 'npc_cat_cleo'],
  },
  npc_home_2: {
    id: 'npc_home_2',
    type: 'npc_home',
    name: 'Whiskers Manor',
    width: 18,
    height: 18,
    blockedCells: [],
    walls: [
      { id: 'w1', x1: 0, y1: 0, x2: 18, y2: 0, provenance: 'earned' },
      { id: 'w2', x1: 18, y1: 0, x2: 18, y2: 18, provenance: 'earned' },
      { id: 'w3', x1: 18, y1: 18, x2: 0, y2: 18, provenance: 'earned' },
      { id: 'w4', x1: 0, y1: 18, x2: 0, y2: 0, provenance: 'earned' },
    ],
    doors: [{ id: 'd1', x: 9, y: 18, orientation: 'horizontal', provenance: 'earned' }],
    objects: [
      {
        id: 'npc2_fireplace',
        catalogId: 'stone_fireplace',
        name: 'Warm Stone Fireplace',
        category: 'decor',
        x: 8,
        y: 2,
        width: 2,
        height: 2,
        interactSpots: [{ x: 9, y: 4 }],
        provenance: 'earned',
      },
    ],
    residentCatIds: ['npc_cat_felix', 'npc_cat_milo', 'npc_cat_hazel'],
  },
  npc_home_3: {
    id: 'npc_home_3',
    type: 'npc_home',
    name: 'Cozy Nook',
    width: 14,
    height: 14,
    blockedCells: [],
    walls: [
      { id: 'w1', x1: 0, y1: 0, x2: 14, y2: 0, provenance: 'earned' },
      { id: 'w2', x1: 14, y1: 0, x2: 14, y2: 14, provenance: 'earned' },
      { id: 'w3', x1: 14, y1: 14, x2: 0, y2: 14, provenance: 'earned' },
      { id: 'w4', x1: 0, y1: 14, x2: 0, y2: 0, provenance: 'earned' },
    ],
    doors: [{ id: 'd1', x: 7, y: 14, orientation: 'horizontal', provenance: 'earned' }],
    objects: [
      {
        id: 'npc3_cushion',
        catalogId: 'floor_cushion',
        name: 'Velvet Floor Cushion',
        category: 'seating',
        x: 5,
        y: 5,
        width: 2,
        height: 2,
        interactSpots: [{ x: 6, y: 7 }],
        provenance: 'earned',
      },
    ],
    residentCatIds: ['npc_cat_luna', 'npc_cat_oliver', 'npc_cat_shadow'],
  },
  park: {
    id: 'park',
    type: 'park',
    name: 'Sunny Meadow Park',
    width: 24,
    height: 24,
    blockedCells: ['10,10', '10,11', '11,10', '11,11'], // Fountain core
    walls: [],
    doors: [],
    objects: [
      {
        id: 'park_fountain',
        catalogId: 'stone_fountain',
        name: 'Sunny Meadow Fountain',
        category: 'decor',
        x: 10,
        y: 10,
        width: 2,
        height: 2,
        interactSpots: [{ x: 10, y: 12 }, { x: 12, y: 10 }],
        provenance: 'earned',
      },
      {
        id: 'park_bench_1',
        catalogId: 'park_bench',
        name: 'Wooden Park Bench',
        category: 'seating',
        x: 5,
        y: 12,
        width: 2,
        height: 1,
        interactSpots: [{ x: 5, y: 13 }],
        provenance: 'earned',
      },
    ],
  },
  shop: {
    id: 'shop',
    type: 'shop',
    name: 'Corner Pet Emporium & Adoption Center',
    width: 18,
    height: 18,
    blockedCells: [],
    walls: [
      { id: 'w1', x1: 0, y1: 0, x2: 18, y2: 0, provenance: 'earned' },
      { id: 'w2', x1: 18, y1: 0, x2: 18, y2: 18, provenance: 'earned' },
      { id: 'w3', x1: 18, y1: 18, x2: 0, y2: 18, provenance: 'earned' },
      { id: 'w4', x1: 0, y1: 18, x2: 0, y2: 0, provenance: 'earned' },
    ],
    doors: [{ id: 'd1', x: 9, y: 18, orientation: 'horizontal', provenance: 'earned' }],
    objects: [
      {
        id: 'shop_counter',
        catalogId: 'merchant_counter',
        name: 'Shopkeeper Counter',
        category: 'storage',
        x: 8,
        y: 3,
        width: 3,
        height: 1,
        interactSpots: [{ x: 9, y: 4 }],
        provenance: 'earned',
      },
      {
        id: 'adoption_pen',
        catalogId: 'adoption_lounge',
        name: 'Kitten & Adoption Playpen',
        category: 'care',
        x: 12,
        y: 10,
        width: 4,
        height: 4,
        interactSpots: [{ x: 11, y: 12 }],
        provenance: 'earned',
      },
    ],
    openingHour: 8,  // 8 AM
    closingHour: 20, // 8 PM
  },
  cafe: {
    id: 'cafe',
    type: 'cafe',
    name: 'Whiskers & Brew Cat Café',
    width: 18,
    height: 18,
    blockedCells: [],
    walls: [
      { id: 'w1', x1: 0, y1: 0, x2: 18, y2: 0, provenance: 'earned' },
      { id: 'w2', x1: 18, y1: 0, x2: 18, y2: 18, provenance: 'earned' },
      { id: 'w3', x1: 18, y1: 18, x2: 0, y2: 18, provenance: 'earned' },
      { id: 'w4', x1: 0, y1: 18, x2: 0, y2: 0, provenance: 'earned' },
    ],
    doors: [{ id: 'd1', x: 9, y: 18, orientation: 'horizontal', provenance: 'earned' }],
    objects: [
      {
        id: 'cafe_bar',
        catalogId: 'coffee_bar',
        name: 'Espresso Bar',
        category: 'storage',
        x: 2,
        y: 2,
        width: 4,
        height: 2,
        interactSpots: [{ x: 4, y: 4 }],
        provenance: 'earned',
      },
      {
        id: 'cafe_table_1',
        catalogId: 'bistro_table',
        name: 'Café Bistro Table',
        category: 'seating',
        x: 10,
        y: 8,
        width: 2,
        height: 2,
        interactSpots: [{ x: 10, y: 10 }],
        provenance: 'earned',
      },
    ],
    openingHour: 7,  // 7 AM
    closingHour: 22, // 10 PM
  },
};
