import { CatRecord, ShopCatalogItem, AdoptionCandidate } from './types';

export const INITIAL_NPC_CATS: Record<string, CatRecord> = {
  npc_cat_barnaby: {
    id: 'npc_cat_barnaby',
    name: 'Barnaby',
    appearance: { bodyColor: '#E67E22', pattern: 'tabby', eyeColor: '#2ECC71', collarColor: '#E74C3C' },
    traits: ['adventurous', 'playful'],
    lifeStage: 'adult',
    ageDays: 45,
    ageMinutes: 45 * 1440,
    lifeStatus: 'living',
    needs: { hunger: 80, hygiene: 85, energy: 90, comfort: 85, social: 75, fun: 80, health: 100 },
    moodScore: 82,
    moodBand: 'happy',
    skills: { hunting: 5, agility: 6, charm: 4, crafting: 2 },
    position: { lotId: 'npc_home_1', x: 5, y: 5 },
    currentAction: null,
    lastRoute: [],
    relationships: {},
    isNpc: true,
    homeLotId: 'npc_home_1',
    npcSchedule: [
      { startHour: 8, endHour: 12, lotId: 'park', activity: 'strolling' },
      { startHour: 12, endHour: 16, lotId: 'cafe', activity: 'napping' },
      { startHour: 16, endHour: 24, lotId: 'npc_home_1', activity: 'resting' },
      { startHour: 0, endHour: 8, lotId: 'npc_home_1', activity: 'sleeping' },
    ],
  },
  npc_cat_cleo: {
    id: 'npc_cat_cleo',
    name: 'Cleo',
    appearance: { bodyColor: '#F39C12', pattern: 'calico', eyeColor: '#3498DB', collarColor: '#9B59B6' },
    traits: ['social', 'affectionate'],
    lifeStage: 'adult',
    ageDays: 50,
    ageMinutes: 50 * 1440,
    lifeStatus: 'living',
    needs: { hunger: 85, hygiene: 90, energy: 85, comfort: 90, social: 85, fun: 75, health: 100 },
    moodScore: 86,
    moodBand: 'happy',
    skills: { hunting: 3, agility: 4, charm: 8, crafting: 3 },
    position: { lotId: 'npc_home_1', x: 6, y: 5 },
    currentAction: null,
    lastRoute: [],
    relationships: {},
    isNpc: true,
    homeLotId: 'npc_home_1',
    npcSchedule: [
      { startHour: 9, endHour: 13, lotId: 'shop', activity: 'browsing' },
      { startHour: 13, endHour: 17, lotId: 'park', activity: 'socializing' },
      { startHour: 17, endHour: 24, lotId: 'npc_home_1', activity: 'grooming' },
      { startHour: 0, endHour: 9, lotId: 'npc_home_1', activity: 'sleeping' },
    ],
  },
  npc_cat_felix: {
    id: 'npc_cat_felix',
    name: 'Felix',
    appearance: { bodyColor: '#2C3E50', pattern: 'tuxedo', eyeColor: '#F1C40F', collarColor: '#1ABC9C' },
    traits: ['greedy', 'curious'],
    lifeStage: 'adult',
    ageDays: 60,
    ageMinutes: 60 * 1440,
    lifeStatus: 'living',
    needs: { hunger: 75, hygiene: 80, energy: 85, comfort: 80, social: 70, fun: 70, health: 100 },
    moodScore: 76,
    moodBand: 'happy',
    skills: { hunting: 6, agility: 5, charm: 5, crafting: 4 },
    position: { lotId: 'npc_home_2', x: 4, y: 4 },
    currentAction: null,
    lastRoute: [],
    relationships: {},
    isNpc: true,
    homeLotId: 'npc_home_2',
    npcSchedule: [
      { startHour: 7, endHour: 11, lotId: 'cafe', activity: 'snacking' },
      { startHour: 11, endHour: 15, lotId: 'shop', activity: 'window shopping' },
      { startHour: 15, endHour: 24, lotId: 'npc_home_2', activity: 'lounging' },
      { startHour: 0, endHour: 7, lotId: 'npc_home_2', activity: 'sleeping' },
    ],
  },
  npc_cat_milo: {
    id: 'npc_cat_milo',
    name: 'Milo',
    appearance: { bodyColor: '#7F8C8D', pattern: 'tabby', eyeColor: '#E67E22', collarColor: '#34495E' },
    traits: ['lazy', 'affectionate'],
    lifeStage: 'elder',
    ageDays: 130,
    ageMinutes: 130 * 1440,
    lifeStatus: 'living',
    needs: { hunger: 70, hygiene: 75, energy: 65, comfort: 95, social: 80, fun: 60, health: 90 },
    moodScore: 78,
    moodBand: 'happy',
    skills: { hunting: 2, agility: 2, charm: 9, crafting: 1 },
    position: { lotId: 'npc_home_2', x: 5, y: 4 },
    currentAction: null,
    lastRoute: [],
    relationships: {},
    isNpc: true,
    homeLotId: 'npc_home_2',
    npcSchedule: [
      { startHour: 10, endHour: 14, lotId: 'park', activity: 'sunbathing' },
      { startHour: 14, endHour: 18, lotId: 'npc_home_2', activity: 'napping' },
      { startHour: 18, endHour: 22, lotId: 'cafe', activity: 'purring' },
      { startHour: 22, endHour: 10, lotId: 'npc_home_2', activity: 'sleeping' },
    ],
  },
  npc_cat_hazel: {
    id: 'npc_cat_hazel',
    name: 'Hazel',
    appearance: { bodyColor: '#D35400', pattern: 'tortoiseshell', eyeColor: '#27AE60', collarColor: '#2980B9' },
    traits: ['curious', 'playful'],
    lifeStage: 'adult',
    ageDays: 35,
    ageMinutes: 35 * 1440,
    lifeStatus: 'living',
    needs: { hunger: 85, hygiene: 85, energy: 95, comfort: 80, social: 80, fun: 90, health: 100 },
    moodScore: 88,
    moodBand: 'happy',
    skills: { hunting: 7, agility: 7, charm: 5, crafting: 3 },
    position: { lotId: 'npc_home_2', x: 6, y: 4 },
    currentAction: null,
    lastRoute: [],
    relationships: {},
    isNpc: true,
    homeLotId: 'npc_home_2',
    npcSchedule: [
      { startHour: 8, endHour: 12, lotId: 'shop', activity: 'exploring' },
      { startHour: 12, endHour: 17, lotId: 'park', activity: 'chasing butterflies' },
      { startHour: 17, endHour: 24, lotId: 'npc_home_2', activity: 'playing' },
      { startHour: 0, endHour: 8, lotId: 'npc_home_2', activity: 'sleeping' },
    ],
  },
  npc_cat_luna: {
    id: 'npc_cat_luna',
    name: 'Luna',
    appearance: { bodyColor: '#ECF0F1', pattern: 'point', eyeColor: '#2980B9', collarColor: '#E74C3C' },
    traits: ['skittish', 'social'],
    lifeStage: 'adult',
    ageDays: 40,
    ageMinutes: 40 * 1440,
    lifeStatus: 'living',
    needs: { hunger: 80, hygiene: 90, energy: 80, comfort: 85, social: 70, fun: 75, health: 100 },
    moodScore: 80,
    moodBand: 'happy',
    skills: { hunting: 4, agility: 8, charm: 7, crafting: 2 },
    position: { lotId: 'npc_home_3', x: 4, y: 4 },
    currentAction: null,
    lastRoute: [],
    relationships: {},
    isNpc: true,
    homeLotId: 'npc_home_3',
    npcSchedule: [
      { startHour: 9, endHour: 13, lotId: 'cafe', activity: 'people watching' },
      { startHour: 13, endHour: 18, lotId: 'park', activity: 'hiding under bench' },
      { startHour: 18, endHour: 24, lotId: 'npc_home_3', activity: 'resting' },
      { startHour: 0, endHour: 9, lotId: 'npc_home_3', activity: 'sleeping' },
    ],
  },
  npc_cat_oliver: {
    id: 'npc_cat_oliver',
    name: 'Oliver',
    appearance: { bodyColor: '#E67E22', pattern: 'striped', eyeColor: '#16A085', collarColor: '#8E44AD' },
    traits: ['adventurous', 'greedy'],
    lifeStage: 'adolescent',
    ageDays: 20,
    ageMinutes: 20 * 1440,
    lifeStatus: 'living',
    needs: { hunger: 90, hygiene: 80, energy: 95, comfort: 75, social: 85, fun: 95, health: 100 },
    moodScore: 87,
    moodBand: 'happy',
    skills: { hunting: 5, agility: 8, charm: 6, crafting: 1 },
    position: { lotId: 'npc_home_3', x: 5, y: 4 },
    currentAction: null,
    lastRoute: [],
    relationships: {},
    isNpc: true,
    homeLotId: 'npc_home_3',
    npcSchedule: [
      { startHour: 8, endHour: 14, lotId: 'park', activity: 'climbing trees' },
      { startHour: 14, endHour: 19, lotId: 'shop', activity: 'sniffing treat bags' },
      { startHour: 19, endHour: 24, lotId: 'npc_home_3', activity: 'eating' },
      { startHour: 0, endHour: 8, lotId: 'npc_home_3', activity: 'sleeping' },
    ],
  },
  npc_cat_shadow: {
    id: 'npc_cat_shadow',
    name: 'Shadow',
    appearance: { bodyColor: '#111111', pattern: 'solid', eyeColor: '#F39C12', collarColor: '#C0392B' },
    traits: ['skittish', 'adventurous'],
    lifeStage: 'adult',
    ageDays: 55,
    ageMinutes: 55 * 1440,
    lifeStatus: 'living',
    needs: { hunger: 85, hygiene: 85, energy: 90, comfort: 80, social: 65, fun: 85, health: 100 },
    moodScore: 81,
    moodBand: 'happy',
    skills: { hunting: 9, agility: 9, charm: 3, crafting: 2 },
    position: { lotId: 'npc_home_3', x: 6, y: 4 },
    currentAction: null,
    lastRoute: [],
    relationships: {},
    isNpc: true,
    homeLotId: 'npc_home_3',
    npcSchedule: [
      { startHour: 10, endHour: 15, lotId: 'park', activity: 'prowling' },
      { startHour: 15, endHour: 20, lotId: 'cafe', activity: 'watching from corner' },
      { startHour: 20, endHour: 24, lotId: 'npc_home_3', activity: 'grooming' },
      { startHour: 0, endHour: 10, lotId: 'npc_home_3', activity: 'sleeping' },
    ],
  },
};

export const INITIAL_SHOP_INVENTORY: ShopCatalogItem[] = [
  { catalogId: 'gourmet_catnip', name: 'Organic Gourmet Catnip', category: 'food', price: 15, stock: 20 },
  { catalogId: 'deluxe_scratching_post', name: 'Deluxe Sisal Scratching Post', category: 'play', price: 85, stock: 5 },
  { catalogId: 'feather_wand_toy', name: 'Interactive Feather Wand', category: 'play', price: 25, stock: 12 },
  { catalogId: 'plush_donut_bed', name: 'Orthopedic Plush Donut Bed', category: 'sleep', price: 120, stock: 4 },
  { catalogId: 'automatic_water_fountain', name: 'Filtered Water Fountain', category: 'care', price: 95, stock: 6 },
];

export const INITIAL_ADOPTION_CANDIDATES: AdoptionCandidate[] = [
  {
    candidateId: 'candidate_whiskers',
    name: 'Whiskers',
    appearance: { bodyColor: '#34495E', pattern: 'tabby', eyeColor: '#2ECC71', collarColor: '#E74C3C' },
    traits: ['affectionate', 'curious'],
    lifeStage: 'adult',
    adoptionFee: 50,
    description: 'A gentle grey tabby who loves cozy laps and warm sunny spots.',
  },
  {
    candidateId: 'candidate_pip',
    name: 'Pip',
    appearance: { bodyColor: '#F1C40F', pattern: 'solid', eyeColor: '#3498DB', collarColor: '#9B59B6' },
    traits: ['playful', 'adventurous'],
    lifeStage: 'adult',
    adoptionFee: 50,
    description: 'A energetic golden cat eager for play and new adventures.',
  },
  {
    candidateId: 'candidate_mochi',
    name: 'Mochi',
    appearance: { bodyColor: '#ECF0F1', pattern: 'calico', eyeColor: '#E67E22', collarColor: '#1ABC9C' },
    traits: ['social', 'lazy'],
    lifeStage: 'adult',
    adoptionFee: 50,
    description: 'A sweet calico who enjoys social snuggles and long naps.',
  },
];
