import { ExpandedFurnitureItem } from './types';
import { LEGACY_30_ITEMS } from './legacy_catalog';

/**
 * Additional 34 items to complete the >= 64 items expanded furniture catalog across 4 room styles:
 * - Cozy Cottage
 * - Modern Cat
 * - Whimsical Play
 * - Rustic Garden
 */
export const EXPANDED_ADDITIONAL_ITEMS: ExpandedFurnitureItem[] = [
  // --- ATLAS 01 ADDITIONAL ITEMS ---
  {
    id: 'kitchen_sink_island',
    displayName: 'Cottage Kitchen Sink Island',
    category: 'kitchen',
    style: 'cozy_cottage',
    costCoins: 160,
    width: 2,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'wash' }, { x: 1, y: 0, label: 'prep' }],
    paletteVariants: ['farmhouse_white', 'sage_green', 'navy_blue'],
    placementType: 'floor',
    needAffordance: { needType: 'hygiene', satisfactionRate: 15, description: 'Clean dishes and food prep' },
    description: 'Spacious kitchen island with built-in sink.',
    assetKey: 'kitchen_sink_island',
    atlas: 'atlas01',
    atlasIndex: 1,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'blush_fridge',
    displayName: 'Pastel Storage Refrigerator',
    category: 'kitchen',
    style: 'cozy_cottage',
    costCoins: 200,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'open' }],
    paletteVariants: ['blush_pink', 'mint_cream', 'butter_yellow'],
    placementType: 'floor',
    needAffordance: { needType: 'hunger', satisfactionRate: 10, description: 'Keeps cat food and fish fresh' },
    description: 'Retro styled refrigerator for treat storage.',
    assetKey: 'blush_fridge',
    atlas: 'atlas01',
    atlasIndex: 2,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'cottage_armchair',
    displayName: 'Floral Reading Armchair',
    category: 'seating',
    style: 'cozy_cottage',
    costCoins: 85,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'curl_up' }],
    paletteVariants: ['floral_chintz', 'linen_beige', 'velvet_rose'],
    placementType: 'floor',
    needAffordance: { needType: 'comfort', satisfactionRate: 20, description: 'Deep soft cushion for reading naps' },
    description: 'Plush single armchair with floral slipcover.',
    assetKey: 'armchair',
    atlas: 'atlas01',
    atlasIndex: 4,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'yarn_basket',
    displayName: 'Rainbow Yarn Play Basket',
    category: 'play',
    style: 'whimsical_play',
    costCoins: 25,
    width: 1,
    height: 1,
    isSolid: false,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'swat_yarn' }],
    paletteVariants: ['woven_wicker', 'pastel_pink', 'sky_blue'],
    placementType: 'floor',
    needAffordance: { needType: 'fun', satisfactionRate: 20, description: 'Tangle and swat colorful wool balls' },
    description: 'Overflowing basket of soft wool yarn balls.',
    assetKey: 'yarn',
    atlas: 'atlas01',
    atlasIndex: 14,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'window_hammock',
    displayName: 'Suction Window Hammock',
    category: 'sleep',
    style: 'modern_cat',
    costCoins: 55,
    width: 1,
    height: 1,
    isSolid: false,
    requiresWall: true,
    allowedRotations: [0, 180],
    interactSpots: [{ x: 0, y: 0, label: 'sway' }],
    paletteVariants: ['canvas_natural', 'charcoal_mesh', 'coral_fleece'],
    placementType: 'wall',
    needAffordance: { needType: 'energy', satisfactionRate: 20, description: 'Elevated sunny window nap' },
    description: 'Window-mounted elevated fabric hammock.',
    assetKey: 'hammock',
    atlas: 'atlas01',
    atlasIndex: 15,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },

  // --- ATLAS 02 ADDITIONAL ITEMS ---
  {
    id: 'cozy_beanbag',
    displayName: 'Fluffy Lounging Beanbag',
    category: 'seating',
    style: 'modern_cat',
    costCoins: 65,
    width: 1,
    height: 1,
    isSolid: false,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'sink_in' }],
    paletteVariants: ['sherpa_white', 'dusty_sage', 'lavender'],
    placementType: 'floor',
    needAffordance: { needType: 'comfort', satisfactionRate: 25, description: 'Molds perfectly to cat bodies' },
    description: 'Ultra-soft squishy beanbag lounger.',
    assetKey: 'beanbag',
    atlas: 'atlas02',
    atlasIndex: 0,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'donut_fleece_bed',
    displayName: 'Self-Warming Donut Bed',
    category: 'sleep',
    style: 'modern_cat',
    costCoins: 70,
    width: 1,
    height: 1,
    isSolid: false,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'curl' }],
    paletteVariants: ['blush_pink', 'mist_gray', 'cream'],
    placementType: 'floor',
    needAffordance: { needType: 'energy', satisfactionRate: 25, description: 'Deep rim bed for anxious cats' },
    description: 'Round plush donut bed that calms and warms.',
    assetKey: 'donutbed',
    atlas: 'atlas02',
    atlasIndex: 3,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'felt_cat_cave',
    displayName: 'Wool Felt Igloo Cave',
    category: 'sleep',
    style: 'modern_cat',
    costCoins: 75,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'hide' }],
    paletteVariants: ['heather_gray', 'mustard_yellow', 'teal'],
    placementType: 'floor',
    needAffordance: { needType: 'comfort', satisfactionRate: 20, description: 'Enclosed quiet hideaway' },
    description: 'Handcrafted wool felt pod for private rest.',
    assetKey: 'felt_cave',
    atlas: 'atlas02',
    atlasIndex: 4,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'auto_puzzle_feeder',
    displayName: 'Smart Timed Puzzle Feeder',
    category: 'care',
    style: 'modern_cat',
    costCoins: 110,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'solve_puzzle' }],
    paletteVariants: ['nordic_white', 'space_gray', 'cyan_accent'],
    placementType: 'floor',
    needAffordance: { needType: 'fun', satisfactionRate: 20, description: 'Mental stimulation while earning kibble' },
    description: 'Interactive feeder dispensing kibble via maze solving.',
    assetKey: 'autofeeder',
    atlas: 'atlas02',
    atlasIndex: 5,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'grand_piano',
    displayName: 'Miniature Grand Piano',
    category: 'skills',
    style: 'cozy_cottage',
    costCoins: 300,
    width: 2,
    height: 2,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'play_keys' }, { x: 1, y: 0, label: 'listen' }],
    paletteVariants: ['ebony_gloss', 'ivory_white', 'mahogany'],
    placementType: 'floor',
    needAffordance: { needType: 'fun', satisfactionRate: 15, description: 'Walk across keys to compose feline melodies' },
    description: 'Elegant piano tuned for feline concerts.',
    assetKey: 'piano',
    atlas: 'atlas02',
    atlasIndex: 11,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'agility_hoop',
    displayName: 'Whimsical Agility Jump Hoop',
    category: 'play',
    style: 'whimsical_play',
    costCoins: 60,
    width: 1,
    height: 1,
    isSolid: false,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'leap' }],
    paletteVariants: ['circus_stripe', 'gold_star', 'neon_green'],
    placementType: 'floor',
    needAffordance: { needType: 'fun', satisfactionRate: 35, description: 'High-energy acrobatics and jumping' },
    description: 'Padded agility ring for acrobatic leaps.',
    assetKey: 'agilityhoop',
    atlas: 'atlas02',
    atlasIndex: 12,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'modern_credenza',
    displayName: 'Low Storage Credenza',
    category: 'storage',
    style: 'modern_cat',
    costCoins: 140,
    width: 2,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'store' }, { x: 1, y: 0, label: 'perch' }],
    paletteVariants: ['walnut_slat', 'white_oak', 'black_metal'],
    placementType: 'floor',
    needAffordance: { needType: 'comfort', satisfactionRate: 10, description: 'Sleek storage and perching sideboard' },
    description: 'Sleek mid-century storage cabinet.',
    assetKey: 'credenza',
    atlas: 'atlas02',
    atlasIndex: 13,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },

  // --- ATLAS 03 ADDITIONAL ITEMS ---
  {
    id: 'mint_pastry_oven',
    displayName: 'Mint Bakery Oven',
    category: 'kitchen',
    style: 'cozy_cottage',
    costCoins: 220,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'bake' }],
    paletteVariants: ['vintage_mint', 'cream_white', 'blush'],
    placementType: 'floor',
    needAffordance: { needType: 'hunger', satisfactionRate: 15, description: 'Bakes fish tarts and catnip cookies' },
    description: 'Pastel baking oven for café treats.',
    assetKey: 'mint_oven',
    atlas: 'atlas03',
    atlasIndex: 0,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'dough_stand_mixer',
    displayName: 'Countertop Stand Dough Mixer',
    category: 'kitchen',
    style: 'cozy_cottage',
    costCoins: 90,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'mix' }],
    paletteVariants: ['cherry_red', 'pistachio_green', 'creamy_vanilla'],
    placementType: 'surface',
    needAffordance: { needType: 'fun', satisfactionRate: 10, description: 'Whisks dough for bakery recipes' },
    description: 'Heavy duty mixer for treat doughs.',
    assetKey: 'doughmixer',
    atlas: 'atlas03',
    atlasIndex: 3,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'breakfast_booth',
    displayName: 'Upholstered Breakfast Booth',
    category: 'seating',
    style: 'cozy_cottage',
    costCoins: 175,
    width: 2,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'snuggle' }, { x: 1, y: 0, label: 'snuggle' }],
    paletteVariants: ['tufted_teal', 'mustard_velvet', 'cherry_vinyl'],
    placementType: 'floor',
    needAffordance: { needType: 'social', satisfactionRate: 25, description: 'Cozy diner booth for group meals' },
    description: 'Plush corner booth for café snuggles.',
    assetKey: 'breakfastbooth',
    atlas: 'atlas03',
    atlasIndex: 5,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'vanity_washbasin',
    displayName: 'Bathroom Vanity Washbasin',
    category: 'care',
    style: 'modern_cat',
    costCoins: 130,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'wash_paws' }],
    paletteVariants: ['marble_brass', 'mat_black', 'terrazzo'],
    placementType: 'floor',
    needAffordance: { needType: 'hygiene', satisfactionRate: 30, description: 'Paw washing and coat grooming' },
    description: 'Modern vanity basin for cat hygiene.',
    assetKey: 'washbasinvanity',
    atlas: 'atlas03',
    atlasIndex: 9,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'laundry_linen_basket',
    displayName: 'Woven Laundry Basket Bed',
    category: 'sleep',
    style: 'cozy_cottage',
    costCoins: 40,
    width: 1,
    height: 1,
    isSolid: false,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'nest' }],
    paletteVariants: ['warm_towel', 'lavender_linen', 'crisp_white'],
    placementType: 'floor',
    needAffordance: { needType: 'energy', satisfactionRate: 20, description: 'Warm fresh laundry pile nap' },
    description: 'Basket filled with warm fluffy towels.',
    assetKey: 'laundrybasket',
    atlas: 'atlas03',
    atlasIndex: 11,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'cafe_pantry_cabinet',
    displayName: 'Tall Kitchen Pantry Cabinet',
    category: 'storage',
    style: 'cozy_cottage',
    costCoins: 120,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'inspect_pantry' }],
    paletteVariants: ['country_cream', 'slate_blue', 'sage'],
    placementType: 'floor',
    needAffordance: { needType: 'hunger', satisfactionRate: 5, description: 'Stores ingredients and treats' },
    description: 'High storage pantry for baking supplies.',
    assetKey: 'pantry',
    atlas: 'atlas03',
    atlasIndex: 12,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'treat_sideboard',
    displayName: 'Carved Treat Sideboard',
    category: 'kitchen',
    style: 'cozy_cottage',
    costCoins: 110,
    width: 2,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'sample_treat' }, { x: 1, y: 0, label: 'sample_treat' }],
    paletteVariants: ['carved_oak', 'distressed_white', 'charcoal'],
    placementType: 'floor',
    needAffordance: { needType: 'hunger', satisfactionRate: 15, description: 'Serves daily treat samples' },
    description: 'Sideboard for displaying treat jars.',
    assetKey: 'treatsideboard',
    atlas: 'atlas03',
    atlasIndex: 14,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'dishwashing_station',
    displayName: 'Commercial Dishwashing Station',
    category: 'kitchen',
    style: 'modern_cat',
    costCoins: 190,
    width: 2,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'sanitize' }, { x: 1, y: 0, label: 'dry' }],
    paletteVariants: ['stainless_steel', 'black_industrial', 'teal_accent'],
    placementType: 'floor',
    needAffordance: { needType: 'hygiene', satisfactionRate: 25, description: 'Keeps café bowls sparkling clean' },
    description: 'High throughput dish cleaner for busy café hours.',
    assetKey: 'dishwashingstation',
    atlas: 'atlas03',
    atlasIndex: 15,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },

  // --- ATLAS 04 ADDITIONAL ITEMS ---
  {
    id: 'royal_canopy_bed',
    displayName: 'Royal Sheer Canopy Bed',
    category: 'sleep',
    style: 'whimsical_play',
    costCoins: 220,
    width: 2,
    height: 2,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'slumber' }, { x: 1, y: 1, label: 'slumber' }],
    paletteVariants: ['gold_drape', 'rose_velvet', 'royal_purple'],
    placementType: 'floor',
    needAffordance: { needType: 'energy', satisfactionRate: 35, description: 'Maximum luxury comfort and sleep restoration' },
    description: 'Ornate draped canopy bed for regal cats.',
    assetKey: 'canopybed',
    atlas: 'atlas04',
    atlasIndex: 0,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'crescent_moon_bed',
    displayName: 'Crescent Moon Hanging Bed',
    category: 'sleep',
    style: 'whimsical_play',
    costCoins: 130,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'dream' }],
    paletteVariants: ['midnight_gold', 'silver_pearl', 'twilight_violet'],
    placementType: 'floor',
    needAffordance: { needType: 'energy', satisfactionRate: 30, description: 'Gentle rocking sleep experience' },
    description: 'Moon-shaped cradle resting on star pedestals.',
    assetKey: 'crescentbed',
    atlas: 'atlas04',
    atlasIndex: 1,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'kitten_bassinet',
    displayName: 'Soft Plush Kitten Bassinet',
    category: 'sleep',
    style: 'cozy_cottage',
    costCoins: 80,
    width: 1,
    height: 1,
    isSolid: false,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'norture' }],
    paletteVariants: ['pastel_pink', 'baby_blue', 'buttercup'],
    placementType: 'floor',
    needAffordance: { needType: 'energy', satisfactionRate: 25, description: 'Safe cozy nest tailored for kittens' },
    description: 'Padded rocking bassinet for newborn litter care.',
    assetKey: 'kittenbassinet',
    atlas: 'atlas04',
    atlasIndex: 2,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'kitten_bunk_bed',
    displayName: 'Double Tier Kitten Bunk',
    category: 'sleep',
    style: 'whimsical_play',
    costCoins: 110,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'top_bunk' }],
    paletteVariants: ['candy_stripe', 'mint_lavender', 'natural_wood'],
    placementType: 'floor',
    needAffordance: { needType: 'energy', satisfactionRate: 25, description: 'Two level sleeping quarters for littermates' },
    description: 'Compact double bunk bed with small wooden ladder.',
    assetKey: 'kittenbunk',
    atlas: 'atlas04',
    atlasIndex: 3,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'scarf_wardrobe_armoire',
    displayName: 'Customization Wardrobe Armoire',
    category: 'storage',
    style: 'cozy_cottage',
    costCoins: 150,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'dress_up' }],
    paletteVariants: ['antique_white', 'walnut_wood', 'sage_paint'],
    placementType: 'floor',
    needAffordance: { needType: 'social', satisfactionRate: 15, description: 'Stores collars, bandanas, bows and career outfits' },
    description: 'Armoire for trying on accessories and career wear.',
    assetKey: 'scarfwardrobe',
    atlas: 'atlas04',
    atlasIndex: 4,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'grooming_vanity_mirror',
    displayName: 'Grooming Vanity with Mirror',
    category: 'care',
    style: 'cozy_cottage',
    costCoins: 120,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'admire' }],
    paletteVariants: ['hollywood_lights', 'gilded_gold', 'blush'],
    placementType: 'floor',
    needAffordance: { needType: 'hygiene', satisfactionRate: 20, description: 'Inspect fur, bowties and career outfits' },
    description: 'Vanity table with glowing round mirror.',
    assetKey: 'vanity',
    atlas: 'atlas04',
    atlasIndex: 5,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'cushioned_reading_nook',
    displayName: 'Tufted Window Reading Nook',
    category: 'seating',
    style: 'cozy_cottage',
    costCoins: 140,
    width: 2,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'curl_up' }, { x: 1, y: 0, label: 'curl_up' }],
    paletteVariants: ['deep_navy', 'forest_velvet', 'oatmeal'],
    placementType: 'floor',
    needAffordance: { needType: 'comfort', satisfactionRate: 30, description: 'Deep tufted alcove for quiet cozy reading' },
    description: 'Deep cushioned alcove bench.',
    assetKey: 'readingnook',
    atlas: 'atlas04',
    atlasIndex: 6,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'starlight_rug',
    displayName: 'Celestial Starlight Rug',
    category: 'decor',
    style: 'whimsical_play',
    costCoins: 50,
    width: 2,
    height: 2,
    isSolid: false,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'lounge' }, { x: 1, y: 1, label: 'lounge' }],
    paletteVariants: ['midnight_navy', 'pastel_lilac', 'gold_foil'],
    placementType: 'floor',
    needAffordance: { needType: 'comfort', satisfactionRate: 15, description: 'Soft star patterned floor covering' },
    description: 'Round rug woven with glowing metallic star thread.',
    assetKey: 'starrug',
    atlas: 'atlas04',
    atlasIndex: 7,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'strawberry_planter',
    displayName: 'Glazed Strawberry Pot',
    category: 'outdoor',
    style: 'rustic_garden',
    costCoins: 65,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'harvest' }],
    paletteVariants: ['ruby_red', 'terracotta', 'emerald_green'],
    placementType: 'floor',
    needAffordance: { needType: 'fun', satisfactionRate: 10, description: 'Grows sweet strawberries in side pockets' },
    description: 'Multi-pocket terracotta pot for berries.',
    assetKey: 'strawberryplanter',
    atlas: 'atlas04',
    atlasIndex: 8,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'garden_potting_bench',
    displayName: 'Rustic Garden Potting Bench',
    category: 'outdoor',
    style: 'rustic_garden',
    costCoins: 110,
    width: 2,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'pot_seeds' }, { x: 1, y: 0, label: 'pot_seeds' }],
    paletteVariants: ['weathered_teal', 'natural_redwood', 'distressed_white'],
    placementType: 'floor',
    needAffordance: { needType: 'fun', satisfactionRate: 15, description: 'Organizes gardening tools and seedling pots' },
    description: 'Outdoor wooden work bench with sink and drawers.',
    assetKey: 'pottingbench',
    atlas: 'atlas04',
    atlasIndex: 9,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'mushroom_stool_set',
    displayName: 'Fairy Mushroom Stool Pair',
    category: 'outdoor',
    style: 'whimsical_play',
    costCoins: 45,
    width: 1,
    height: 1,
    isSolid: false,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'perch_top' }],
    paletteVariants: ['red_white_dots', 'pastel_purple', 'glowing_teal'],
    placementType: 'floor',
    needAffordance: { needType: 'fun', satisfactionRate: 20, description: 'Playful toadstool perches' },
    description: 'Pair of carved fly-agaric mushroom stools.',
    assetKey: 'mushroomseat',
    atlas: 'atlas04',
    atlasIndex: 11,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'porch_swing',
    displayName: 'Garden Wicker Porch Swing',
    category: 'outdoor',
    style: 'rustic_garden',
    costCoins: 160,
    width: 2,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'swing' }, { x: 1, y: 0, label: 'swing' }],
    paletteVariants: ['honey_wicker', 'painted_white', 'espresso_rattan'],
    placementType: 'floor',
    needAffordance: { needType: 'comfort', satisfactionRate: 30, description: 'Gently swinging outdoor bench' },
    description: 'Hanging wicker porch swing with plush cushions.',
    assetKey: 'porchswing',
    atlas: 'atlas04',
    atlasIndex: 12,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'birdbath_fountain',
    displayName: 'Tiered Birdbath Fountain',
    category: 'outdoor',
    style: 'rustic_garden',
    costCoins: 125,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'watch_birds' }],
    paletteVariants: ['weathered_stone', 'bronze_patina', 'terracotta'],
    placementType: 'floor',
    needAffordance: { needType: 'hydration', satisfactionRate: 20, description: 'Flowing water and bird watching entertainment' },
    description: 'Stone garden fountain attracting songbirds.',
    assetKey: 'birdbathfountain',
    atlas: 'atlas04',
    atlasIndex: 13,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'rose_flower_trellis',
    displayName: 'Climbing Rose Flower Trellis',
    category: 'outdoor',
    style: 'rustic_garden',
    costCoins: 75,
    width: 1,
    height: 1,
    isSolid: true,
    requiresWall: true,
    allowedRotations: [0, 180],
    interactSpots: [{ x: 0, y: 0, label: 'sniff_roses' }],
    paletteVariants: ['crimson_roses', 'white_jasmine', 'pink_clematis'],
    placementType: 'wall',
    needAffordance: { needType: 'fun', satisfactionRate: 10, description: 'Fragrant flowering vine climbing grid' },
    description: 'Wooden wall lattice covered in fragrant roses.',
    assetKey: 'flowertrellis',
    atlas: 'atlas04',
    atlasIndex: 14,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'wicker_lounger',
    displayName: 'Rattan Sunbed Lounger',
    category: 'outdoor',
    style: 'rustic_garden',
    costCoins: 95,
    width: 2,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'bask' }, { x: 1, y: 0, label: 'bask' }],
    paletteVariants: ['natural_rattan', 'whitewash', 'dark_teak'],
    placementType: 'floor',
    needAffordance: { needType: 'comfort', satisfactionRate: 25, description: 'Reclining sunbed for garden naps' },
    description: 'Contoured rattan sun lounger with soft cushion.',
    assetKey: 'wickerlounger',
    atlas: 'atlas04',
    atlasIndex: 15,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
];

/**
 * Total combined catalog of all 64 items (30 legacy + 34 expanded).
 */
export const FULL_EXPANDED_FURNITURE_CATALOG: ExpandedFurnitureItem[] = [
  ...LEGACY_30_ITEMS,
  ...EXPANDED_ADDITIONAL_ITEMS,
];
