import { ExpandedFurnitureItem } from './types';

/**
 * 30 Original / Legacy Furniture IDs required for full backward compatibility:
 * 1. food_bowl
 * 2. water_fountain
 * 3. cat_bed_basic
 * 4. scratching_post
 * 5. litter_box
 * 6. feather_toy
 * 7. easel
 * 8. garden_planter
 * 9. cozy_sofa
 * 10. dining_table
 * 11. bookshelf
 * 12. floor_lamp
 * 13. monstera_plant
 * 14. rug_flower
 * 15. grooming_arch
 * 16. laser_pointer_turret
 * 17. cafe_counter
 * 18. cafe_espresso_machine
 * 19. cafe_pastry_display
 * 20. cafe_table
 * 21. cafe_chair
 * 22. wall_clock
 * 23. window_bench
 * 24. wall_shelf
 * 25. pet_bathtub
 * 26. cat_tree_deluxe
 * 27. cardboard_box
 * 28. crinkle_tunnel
 * 29. memorial_statue
 * 30. outdoor_bench
 */

export const LEGACY_30_ITEMS: ExpandedFurnitureItem[] = [
  {
    id: 'food_bowl',
    displayName: 'Classic Food Bowl',
    category: 'care',
    style: 'cozy_cottage',
    costCoins: 25,
    width: 1,
    height: 1,
    isSolid: false,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'eat' }],
    paletteVariants: ['ceramic_white', 'pastel_pink', 'mint_green'],
    placementType: 'floor',
    needAffordance: { needType: 'hunger', satisfactionRate: 20, description: 'Fills hunger when stocked' },
    description: 'A sturdy ceramic food bowl.',
    assetKey: 'food_bowl',
    atlas: 'atlas01',
    atlasIndex: 8,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'water_fountain',
    displayName: 'Drinking Water Fountain',
    category: 'care',
    style: 'modern_cat',
    costCoins: 45,
    width: 1,
    height: 1,
    isSolid: false,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'drink' }],
    paletteVariants: ['cyan_stream', 'snow_white', 'slate_gray'],
    placementType: 'floor',
    needAffordance: { needType: 'hydration', satisfactionRate: 25, description: 'Provides fresh flowing water' },
    description: 'Continuous fresh filtered water fountain.',
    assetKey: 'drinking_fountain',
    atlas: 'atlas01',
    atlasIndex: 9,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'cat_bed_basic',
    displayName: 'Cozy Floral Cat Bed',
    category: 'sleep',
    style: 'cozy_cottage',
    costCoins: 50,
    width: 1,
    height: 1,
    isSolid: false,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'sleep' }],
    paletteVariants: ['floral_rose', 'lavender_dream', 'cream_fluff'],
    placementType: 'floor',
    needAffordance: { needType: 'energy', satisfactionRate: 15, description: 'Restores energy during naps' },
    description: 'Soft floral plush bed for cat naps.',
    assetKey: 'floral_bed',
    atlas: 'atlas01',
    atlasIndex: 3,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'scratching_post',
    displayName: 'Sisal Scratch Post',
    category: 'play',
    style: 'cozy_cottage',
    costCoins: 35,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'scratch' }],
    paletteVariants: ['natural_rope', 'sage_wrap', 'tan_jute'],
    placementType: 'floor',
    needAffordance: { needType: 'scratch', satisfactionRate: 30, description: 'Satisfies claw scratching urge' },
    description: 'Tall sisal post that keeps claws sharp and sofa safe.',
    assetKey: 'groomingarch_scratchpost',
    atlas: 'atlas02',
    atlasIndex: 6,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'litter_box',
    displayName: 'Covered Litter Cabinet',
    category: 'care',
    style: 'cozy_cottage',
    costCoins: 60,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'use_litter' }],
    paletteVariants: ['pastel_blue', 'stone_gray', 'sage_green'],
    placementType: 'floor',
    needAffordance: { needType: 'hygiene', satisfactionRate: 35, description: 'Provides private clean hygiene spot' },
    description: 'Covered litter box cabinet maintaining fresh air.',
    assetKey: 'covered_litterbox',
    atlas: 'atlas01',
    atlasIndex: 7,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'feather_toy',
    displayName: 'Feather Wand Rack',
    category: 'play',
    style: 'whimsical_play',
    costCoins: 30,
    width: 1,
    height: 1,
    isSolid: false,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'pounce' }],
    paletteVariants: ['rainbow_feathers', 'coral_plumage', 'gold_feathers'],
    placementType: 'floor',
    needAffordance: { needType: 'fun', satisfactionRate: 25, description: 'Playful feather wand for pouncing' },
    description: 'Rack with dangling colorful feathers.',
    assetKey: 'featherwand_rack',
    atlas: 'atlas02',
    atlasIndex: 9,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'easel',
    displayName: 'Art Studio Easel',
    category: 'skills',
    style: 'cozy_cottage',
    costCoins: 120,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'paint' }],
    paletteVariants: ['natural_wood', 'mahogany', 'paint_splattered'],
    placementType: 'floor',
    needAffordance: { needType: 'fun', satisfactionRate: 10, description: 'Grows painting skill and creates artwork' },
    description: 'Wooden easel for creative feline painting.',
    assetKey: 'easel',
    atlas: 'atlas01',
    atlasIndex: 10,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'garden_planter',
    displayName: 'Herb Garden Planter',
    category: 'skills',
    style: 'rustic_garden',
    costCoins: 80,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'tend' }],
    paletteVariants: ['terra_cotta', 'rustic_oak', 'moss_green'],
    placementType: 'floor',
    needAffordance: { needType: 'fun', satisfactionRate: 10, description: 'Grows catnip, tomatoes and strawberries' },
    description: 'Wooden planter box for growing crops.',
    assetKey: 'herbplanter',
    atlas: 'atlas02',
    atlasIndex: 10,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'cozy_sofa',
    displayName: 'Cozy Cottage Sofa',
    category: 'seating',
    style: 'cozy_cottage',
    costCoins: 150,
    width: 2,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'lounge' }, { x: 1, y: 0, label: 'lounge' }],
    paletteVariants: ['cream_fabric', 'sage_linen', 'dusty_rose'],
    placementType: 'floor',
    needAffordance: { needType: 'comfort', satisfactionRate: 20, description: 'High comfort seating for two' },
    description: 'Plush sofa perfect for afternoon lounging.',
    assetKey: 'sofa',
    atlas: 'atlas01',
    atlasIndex: 0,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'dining_table',
    displayName: 'Low Dining Table',
    category: 'seating',
    style: 'cozy_cottage',
    costCoins: 100,
    width: 2,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90],
    interactSpots: [{ x: 0, y: 0, label: 'sit' }, { x: 1, y: 0, label: 'sit' }],
    paletteVariants: ['warm_pine', 'distressed_white', 'walnut'],
    placementType: 'floor',
    needAffordance: { needType: 'social', satisfactionRate: 15, description: 'Gathering spot for dining together' },
    description: 'Low wooden table designed for cat households.',
    assetKey: 'lowdiningtable',
    atlas: 'atlas03',
    atlasIndex: 4,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'bookshelf',
    displayName: 'Story Nook Bookshelf',
    category: 'storage',
    style: 'cozy_cottage',
    costCoins: 110,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'perch' }],
    paletteVariants: ['warm_oak', 'antique_white', 'navy_blue'],
    placementType: 'floor',
    needAffordance: { needType: 'fun', satisfactionRate: 10, description: 'Climb and inspect cozy stories' },
    description: 'Tall bookcase with sturdy cat-climbing shelves.',
    assetKey: 'bookshelf',
    atlas: 'atlas01',
    atlasIndex: 11,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'floor_lamp',
    displayName: 'Warm Ambient Floor Lamp',
    category: 'decor',
    style: 'cozy_cottage',
    costCoins: 40,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'bask' }],
    paletteVariants: ['brass_warm', 'black_matte', 'rose_gold'],
    placementType: 'floor',
    needAffordance: { needType: 'comfort', satisfactionRate: 5, description: 'Warm glowing ambient light' },
    description: 'Tall floor lamp casting a warm cozy glow.',
    assetKey: 'floorlamp',
    atlas: 'atlas01',
    atlasIndex: 12,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'monstera_plant',
    displayName: 'Potted Monstera Plant',
    category: 'decor',
    style: 'rustic_garden',
    costCoins: 35,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'sniff' }],
    paletteVariants: ['terracotta_pot', 'white_ceramic', 'woven_basket'],
    placementType: 'floor',
    needAffordance: { needType: 'fun', satisfactionRate: 5, description: 'Lush greenery to sniff and admire' },
    description: 'Cat-friendly monstera bring natural green indoors.',
    assetKey: 'monstera',
    atlas: 'atlas01',
    atlasIndex: 13,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'rug_flower',
    displayName: 'Blossom Flower Rug',
    category: 'decor',
    style: 'cozy_cottage',
    costCoins: 45,
    width: 2,
    height: 2,
    isSolid: false,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'roll' }, { x: 1, y: 1, label: 'roll' }],
    paletteVariants: ['daisy_yellow', 'rose_pink', 'forget_me_not_blue'],
    placementType: 'floor',
    needAffordance: { needType: 'comfort', satisfactionRate: 10, description: 'Soft textured rug for rolling' },
    description: 'Large flower-shaped woven rug.',
    assetKey: 'flower_rug',
    atlas: 'atlas01',
    atlasIndex: 5,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'grooming_arch',
    displayName: 'Self-Grooming Arch',
    category: 'care',
    style: 'modern_cat',
    costCoins: 40,
    width: 1,
    height: 1,
    isSolid: false,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'rub' }],
    paletteVariants: ['charcoal_bristles', 'teal_bristles', 'cream_bristles'],
    placementType: 'floor',
    needAffordance: { needType: 'hygiene', satisfactionRate: 20, description: 'Self-brushing arch for fur care' },
    description: 'Bristled arch that massages and collects loose fur.',
    assetKey: 'groomingarch',
    atlas: 'atlas02',
    atlasIndex: 6,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'laser_pointer_turret',
    displayName: 'Automatic Laser Turret',
    category: 'play',
    style: 'modern_cat',
    costCoins: 85,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'chase' }],
    paletteVariants: ['sleek_white', 'matte_black', 'mint_accent'],
    placementType: 'floor',
    needAffordance: { needType: 'fun', satisfactionRate: 35, description: 'Exciting automated red dot laser chase' },
    description: 'Rotating laser beam turret for energetic chase play.',
    assetKey: 'laser_turret',
    atlas: 'atlas02',
    atlasIndex: 8,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'cafe_counter',
    displayName: 'Café Espresso Bar Counter',
    category: 'kitchen',
    style: 'modern_cat',
    costCoins: 250,
    width: 2,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'serve' }, { x: 1, y: 0, label: 'order' }],
    paletteVariants: ['polished_marble', 'warm_teak', 'black_granite'],
    placementType: 'floor',
    needAffordance: { needType: 'social', satisfactionRate: 20, description: 'Core café business work counter' },
    description: 'Espresso service bar for running the community café.',
    assetKey: 'espressobar',
    atlas: 'atlas03',
    atlasIndex: 7,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'cafe_espresso_machine',
    displayName: 'Professional Espresso Barista Unit',
    category: 'kitchen',
    style: 'modern_cat',
    costCoins: 180,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'brew' }],
    paletteVariants: ['chrome_steel', 'mint_enamel', 'rose_gold'],
    placementType: 'surface',
    needAffordance: { needType: 'hunger', satisfactionRate: 15, description: 'Brews warm lattes and drinks' },
    description: 'Double-group espresso machine for specialty drinks.',
    assetKey: 'espressobar',
    atlas: 'atlas03',
    atlasIndex: 7,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'cafe_pastry_display',
    displayName: 'Glass Pastry Display Case',
    category: 'kitchen',
    style: 'modern_cat',
    costCoins: 160,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'browse' }],
    paletteVariants: ['clear_glass', 'gold_trim', 'black_frame'],
    placementType: 'floor',
    needAffordance: { needType: 'hunger', satisfactionRate: 20, description: 'Holds freshly baked cat treats and pies' },
    description: 'Temperature-controlled display for cat treats.',
    assetKey: 'pastrydisplay',
    atlas: 'atlas03',
    atlasIndex: 13,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'cafe_table',
    displayName: 'Flower Café Table',
    category: 'seating',
    style: 'cozy_cottage',
    costCoins: 75,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'dine' }],
    paletteVariants: ['bistrot_white', 'wrought_iron', 'blush_pink'],
    placementType: 'floor',
    needAffordance: { needType: 'social', satisfactionRate: 15, description: 'Small cafe table for intimate visits' },
    description: 'Charming round table for café visitors.',
    assetKey: 'flowercafetable',
    atlas: 'atlas03',
    atlasIndex: 6,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'cafe_chair',
    displayName: 'Dining Side Chair',
    category: 'seating',
    style: 'cozy_cottage',
    costCoins: 40,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'sit' }],
    paletteVariants: ['oak_wood', 'painted_white', 'charcoal'],
    placementType: 'floor',
    needAffordance: { needType: 'comfort', satisfactionRate: 10, description: 'Comfortable dining seat' },
    description: 'Matching dining chair for café and home tables.',
    assetKey: 'diningchair',
    atlas: 'atlas02',
    atlasIndex: 1,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'wall_clock',
    displayName: 'Cuckoo Cat Wall Clock',
    category: 'decor',
    style: 'cozy_cottage',
    costCoins: 35,
    width: 1,
    height: 1,
    isSolid: false,
    requiresWall: true,
    allowedRotations: [0, 180],
    interactSpots: [{ x: 0, y: 0, label: 'watch' }],
    paletteVariants: ['cherry_wood', 'mint_green', 'pastel_yellow'],
    placementType: 'wall',
    needAffordance: { needType: 'fun', satisfactionRate: 5, description: 'Tail wags with clock ticks' },
    description: 'Wall clock with swinging cat tail pendulum.',
    assetKey: 'wall_clock',
    atlas: 'legacy',
    artStatus: 'art_needed',
    schemaVersion: 1,
  },
  {
    id: 'window_bench',
    displayName: 'Sunlit Window Bench',
    category: 'seating',
    style: 'cozy_cottage',
    costCoins: 90,
    width: 2,
    height: 1,
    isSolid: true,
    requiresWall: true,
    allowedRotations: [0, 180],
    interactSpots: [{ x: 0, y: 0, label: 'sunbathe' }, { x: 1, y: 0, label: 'sunbathe' }],
    paletteVariants: ['cushioned_cream', 'velvet_teal', 'yellow_check'],
    placementType: 'wall',
    needAffordance: { needType: 'comfort', satisfactionRate: 25, description: 'Warm sunbathing spot near windows' },
    description: 'Cushioned bench fitted under windows for sunbathing.',
    assetKey: 'windowbench',
    atlas: 'atlas02',
    atlasIndex: 2,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'wall_shelf',
    displayName: 'Climbing Wall Shelf',
    category: 'play',
    style: 'modern_cat',
    costCoins: 45,
    width: 1,
    height: 1,
    isSolid: false,
    requiresWall: true,
    allowedRotations: [0, 180],
    interactSpots: [{ x: 0, y: 0, label: 'climb' }],
    paletteVariants: ['natural_birch', 'white_lacquer', 'espresso'],
    placementType: 'wall',
    needAffordance: { needType: 'fun', satisfactionRate: 20, description: 'Elevated shelf satisfying climb instincts' },
    description: 'Sturdy wall-mounted step for vertical exploration.',
    assetKey: 'wall_shelf',
    atlas: 'legacy',
    artStatus: 'art_needed',
    schemaVersion: 1,
  },
  {
    id: 'pet_bathtub',
    displayName: 'Grooming Wash Basin',
    category: 'care',
    style: 'cozy_cottage',
    costCoins: 110,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'bathe' }],
    paletteVariants: ['porcelain_white', 'mint_tile', 'brass_fixtures'],
    placementType: 'floor',
    needAffordance: { needType: 'hygiene', satisfactionRate: 40, description: 'Deep hygiene wash and bubble bath' },
    description: 'Cat-sized clawfoot washing tub.',
    assetKey: 'groomingtub',
    atlas: 'atlas03',
    atlasIndex: 8,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'cat_tree_deluxe',
    displayName: 'Multi-Level Scratching Tower',
    category: 'play',
    style: 'whimsical_play',
    costCoins: 210,
    width: 2,
    height: 2,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'climb' }, { x: 1, y: 1, label: 'perch' }],
    paletteVariants: ['beige_plush', 'forest_moss', 'dusty_pink'],
    placementType: 'floor',
    needAffordance: { needType: 'fun', satisfactionRate: 40, description: 'Ultimate climbing, perching and scratching tower' },
    description: 'Grand multi-level cat tree with hammock and condos.',
    assetKey: 'scratch_tower',
    atlas: 'atlas01',
    atlasIndex: 6,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'cardboard_box',
    displayName: 'Favorite Cardboard Box',
    category: 'play',
    style: 'whimsical_play',
    costCoins: 10,
    width: 1,
    height: 1,
    isSolid: false,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'pounce_in' }],
    paletteVariants: ['kraft_brown', 'express_delivery', 'smile_box'],
    placementType: 'floor',
    needAffordance: { needType: 'fun', satisfactionRate: 30, description: 'Irresistible hiding and napping spot' },
    description: 'Simple brown cardboard box that cats prefer over everything.',
    assetKey: 'cardboardbox',
    atlas: 'atlas02',
    atlasIndex: 4,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'crinkle_tunnel',
    displayName: 'Crinkle Play Tunnel',
    category: 'play',
    style: 'whimsical_play',
    costCoins: 35,
    width: 2,
    height: 1,
    isSolid: false,
    allowedRotations: [0, 90],
    interactSpots: [{ x: 0, y: 0, label: 'dash_through' }, { x: 1, y: 0, label: 'dash_through' }],
    paletteVariants: ['neon_magenta', 'cheery_yellow', 'sky_stripe'],
    placementType: 'floor',
    needAffordance: { needType: 'fun', satisfactionRate: 30, description: 'Noisy crinkle tunnel for zoomies' },
    description: 'Flexible tunnel that crinkles with every step.',
    assetKey: 'crinkletunnel',
    atlas: 'atlas02',
    atlasIndex: 7,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
  {
    id: 'memorial_statue',
    displayName: 'Stone Cat Memorial Statue',
    category: 'decor',
    style: 'cozy_cottage',
    costCoins: 100,
    width: 1,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'remember' }],
    paletteVariants: ['granite_gray', 'marble_white', 'mossy_stone'],
    placementType: 'floor',
    needAffordance: { needType: 'social', satisfactionRate: 10, description: 'Honors beloved cats with quiet visits' },
    description: 'Peaceful stone carving honoring family history.',
    assetKey: 'memorial_statue',
    atlas: 'legacy',
    artStatus: 'art_needed',
    schemaVersion: 1,
  },
  {
    id: 'outdoor_bench',
    displayName: 'Rustic Picnic Bench',
    category: 'outdoor',
    style: 'rustic_garden',
    costCoins: 85,
    width: 2,
    height: 1,
    isSolid: true,
    allowedRotations: [0, 90, 180, 270],
    interactSpots: [{ x: 0, y: 0, label: 'rest' }, { x: 1, y: 0, label: 'rest' }],
    paletteVariants: ['weathered_cedar', 'white_paint', 'forest_green'],
    placementType: 'floor',
    needAffordance: { needType: 'comfort', satisfactionRate: 15, description: 'Garden seating for sunny outdoor rest' },
    description: 'Sturdy wooden garden bench.',
    assetKey: 'picnictable',
    atlas: 'atlas04',
    atlasIndex: 10,
    artStatus: 'verified_atlas',
    schemaVersion: 1,
  },
];
