/**
 * Cat Catalog Manifest
 *
 * Owned path: src/content/cats/catalog.ts
 *
 * Contains:
 * - 42 domestic breed entries + domestic coat mix variants (sourced from official TICA/CFA references)
 * - 8 wild cat species entries (Feline Taxonomy)
 * - 8 original fantasy form entries
 * - Clear distinction between biological breed, coat pattern, wild type, and fantasy species.
 * - Initial coordinator art batch seed mappings vs missing art flags.
 */

import { CatCatalogEntry, CatalogSummary } from './types';

export const DOMESTIC_BREEDS_CATALOG: CatCatalogEntry[] = [
  {
    id: 'abyssinian',
    displayName: 'Abyssinian',
    category: 'domestic',
    gameRarity: 'uncommon',
    eligibleDiscoveryLocations: ['park', 'shop_district', 'home_neighborhood'],
    eligibleDiscoveryConditions: { locationIds: ['park', 'shop_district', 'home_neighborhood'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'solid',
      bodyBuild: 'slender',
      earType: 'large_pointed',
      tailType: 'full',
      primaryColor: 'ruddy_burnt_sienna',
      secondaryColor: 'ticked_black',
      eyeColor: 'gold',
    },
    portraitAssetKey: 'art_needed:portrait:abyssinian',
    bodyAssetKey: 'art_needed:body:abyssinian',
    animationAssetKeys: ['art_needed:anim:abyssinian:walk', 'art_needed:anim:abyssinian:idle'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Enjoys sunlit patches near high vantage points in the park.',
    description: 'A agile, slender domestic cat breed with distinctive ticked coats and lively curiosity.',
    provenance: {
      sourceOrganization: 'TICA',
      citationUrl: 'https://tica.org/ticas-breeds/browse-all-breeds/#abyssinian',
      referenceNotes: 'Official TICA breed standard: lithe body, large ears, ticked agouti coat.',
    },
  },
  {
    id: 'american_shorthair',
    displayName: 'American Shorthair',
    category: 'domestic',
    gameRarity: 'common',
    eligibleDiscoveryLocations: ['home_neighborhood', 'park', 'cafe'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'park', 'cafe'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'tabby',
      bodyBuild: 'medium',
      earType: 'straight',
      tailType: 'full',
      primaryColor: 'silver_grey',
      secondaryColor: 'charcoal_stripes',
      eyeColor: 'green',
    },
    portraitAssetKey: 'silver-tabby', // Batch seed match
    bodyAssetKey: 'silver-tabby',
    animationAssetKeys: ['silver-tabby:walk', 'silver-tabby:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Friendly neighbor cat often resting near garden fences.',
    description: 'An adaptable, sturdy domestic breed known for easygoing temperaments and classic silver tabby patterning.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/american-shorthair/',
      referenceNotes: 'Official CFA breed standard: muscular body, dense coat, classic silver tabby pattern.',
    },
  },
  {
    id: 'american_wirehair',
    displayName: 'American Wirehair',
    category: 'domestic',
    gameRarity: 'uncommon',
    eligibleDiscoveryLocations: ['home_neighborhood', 'shop_district'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'shop_district'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'bicolor',
      bodyBuild: 'medium',
      earType: 'straight',
      tailType: 'full',
      primaryColor: 'cream',
      secondaryColor: 'brown',
      eyeColor: 'amber',
    },
    portraitAssetKey: 'art_needed:portrait:american_wirehair',
    bodyAssetKey: 'art_needed:body:american_wirehair',
    animationAssetKeys: ['art_needed:anim:american_wirehair:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Recognized by its resilient, springy wire coat texture.',
    description: 'A quiet, resilient cat breed originating from a natural mutation in New York.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/american-wirehair/',
      referenceNotes: 'Official CFA breed standard: ringlet or crimped coat texture.',
    },
  },
  {
    id: 'american_curl',
    displayName: 'American Curl',
    category: 'domestic',
    gameRarity: 'uncommon',
    eligibleDiscoveryLocations: ['park', 'cafe'],
    eligibleDiscoveryConditions: { locationIds: ['park', 'cafe'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'medium',
      coatPattern: 'solid',
      bodyBuild: 'slender',
      earType: 'curled',
      tailType: 'plumed',
      primaryColor: 'peach_cream',
      eyeColor: 'aqua',
    },
    portraitAssetKey: 'art_needed:portrait:american_curl',
    bodyAssetKey: 'art_needed:body:american_curl',
    animationAssetKeys: ['art_needed:anim:american_curl:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Noticeable backward curling ears that give a buoyant expression.',
    description: 'An affectionate domestic cat famous for distinctive ears that curl gracefully backward.',
    provenance: {
      sourceOrganization: 'TICA',
      citationUrl: 'https://tica.org/ticas-breeds/browse-all-breeds/#american-curl',
      referenceNotes: 'Official TICA standard: graceful ear curl, walnut-shaped eyes.',
    },
  },
  {
    id: 'balinese',
    displayName: 'Balinese',
    category: 'domestic',
    gameRarity: 'rare_domestic',
    eligibleDiscoveryLocations: ['cafe', 'park'],
    eligibleDiscoveryConditions: { locationIds: ['cafe', 'park'], timeOfDay: 'day' },
    appearanceFlags: {
      coatLength: 'long',
      coatPattern: 'colorpoint',
      bodyBuild: 'slender',
      earType: 'large_pointed',
      tailType: 'plumed',
      primaryColor: 'cream_ivory',
      secondaryColor: 'seal_point',
      eyeColor: 'deep_blue',
    },
    portraitAssetKey: 'art_needed:portrait:balinese',
    bodyAssetKey: 'art_needed:body:balinese',
    animationAssetKeys: ['art_needed:anim:balinese:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Silky longhair colorpoint with a graceful stance around pleasant cafes.',
    description: 'A long-haired variation of the Siamese known for elegance and vocal affection.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/balinese/',
      referenceNotes: 'Official CFA breed standard: svelte body, sapphire blue eyes, silky plume tail.',
    },
  },
  {
    id: 'bengal',
    displayName: 'Bengal',
    category: 'domestic',
    gameRarity: 'rare_domestic',
    eligibleDiscoveryLocations: ['park', 'wild_fringe'],
    eligibleDiscoveryConditions: { locationIds: ['park', 'wild_fringe'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'rosette',
      bodyBuild: 'muscular',
      earType: 'straight',
      tailType: 'full',
      primaryColor: 'warm_gold',
      secondaryColor: 'black_rosettes',
      eyeColor: 'emerald_green',
    },
    portraitAssetKey: 'art_needed:portrait:bengal',
    bodyAssetKey: 'art_needed:body:bengal',
    animationAssetKeys: ['art_needed:anim:bengal:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Loves water and active play near stream banks in the park.',
    description: 'A striking domestic cat with wild leopard-like rosettes and high athletic energy.',
    provenance: {
      sourceOrganization: 'TICA',
      citationUrl: 'https://tica.org/ticas-breeds/browse-all-breeds/#bengal',
      referenceNotes: 'Official TICA standard: rosetted or marbled coat glitter effect.',
    },
  },
  {
    id: 'birman',
    displayName: 'Birman',
    category: 'domestic',
    gameRarity: 'uncommon',
    eligibleDiscoveryLocations: ['home_neighborhood', 'cafe'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'cafe'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'long',
      coatPattern: 'colorpoint',
      bodyBuild: 'medium',
      earType: 'straight',
      tailType: 'plumed',
      primaryColor: 'eggshell_white',
      secondaryColor: 'chocolate_point',
      eyeColor: 'sapphire_blue',
    },
    portraitAssetKey: 'art_needed:portrait:birman',
    bodyAssetKey: 'art_needed:body:birman',
    animationAssetKeys: ['art_needed:anim:birman:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Always wears four distinctive pure white gloved paws.',
    description: 'The Sacred Cat of Burma, known for gentle nature, point coloration, and white paws.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/birman/',
      referenceNotes: 'Official CFA standard: stocky build, blue eyes, immaculate white gloves.',
    },
  },
  {
    id: 'bombay',
    displayName: 'Bombay',
    category: 'domestic',
    gameRarity: 'uncommon',
    eligibleDiscoveryLocations: ['home_neighborhood', 'shop_district'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'shop_district'], timeOfDay: 'night' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'solid',
      bodyBuild: 'compact',
      earType: 'rounded',
      tailType: 'full',
      primaryColor: 'jet_black',
      eyeColor: 'copper_gold',
    },
    portraitAssetKey: 'black', // Batch seed match
    bodyAssetKey: 'black',
    animationAssetKeys: ['black:walk', 'black:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Sleek black coat resembles a mini panther strolling quietly at dusk.',
    description: 'A parlor panther breed with a shimmering jet-black coat and brilliant copper eyes.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/bombay/',
      referenceNotes: 'Official CFA standard: satin sheen black coat, copper-gold eyes, muscular build.',
    },
  },
  {
    id: 'british_shorthair',
    displayName: 'British Shorthair',
    category: 'domestic',
    gameRarity: 'common',
    eligibleDiscoveryLocations: ['home_neighborhood', 'shop_district', 'cafe'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'shop_district', 'cafe'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'solid',
      bodyBuild: 'cobbly',
      earType: 'straight',
      tailType: 'full',
      primaryColor: 'blue_grey',
      eyeColor: 'amber_orange',
    },
    portraitAssetKey: 'art_needed:portrait:british_shorthair',
    bodyAssetKey: 'art_needed:body:british_shorthair',
    animationAssetKeys: ['art_needed:anim:british_shorthair:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Plump round cheeks and calm, dignity-loving posture.',
    description: 'An ancient British domestic breed with dense plush coat and calm, easygoing character.',
    provenance: {
      sourceOrganization: 'TICA',
      citationUrl: 'https://tica.org/ticas-breeds/browse-all-breeds/#british-shorthair',
      referenceNotes: 'Official TICA standard: round head, dense plush blue coat, compact cobby body.',
    },
  },
  {
    id: 'british_longhair',
    displayName: 'British Longhair',
    category: 'domestic',
    gameRarity: 'uncommon',
    eligibleDiscoveryLocations: ['home_neighborhood', 'cafe'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'cafe'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'long',
      coatPattern: 'solid',
      bodyBuild: 'cobbly',
      earType: 'straight',
      tailType: 'plumed',
      primaryColor: 'soft_blue',
      eyeColor: 'copper',
    },
    portraitAssetKey: 'blue-longhair', // Batch seed match
    bodyAssetKey: 'blue-longhair',
    animationAssetKeys: ['blue-longhair:walk', 'blue-longhair:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Luxurious thick coat with a serene countenance near cozy cafe chairs.',
    description: 'The longhair companion to the British Shorthair, featuring a majestic thick coat.',
    provenance: {
      sourceOrganization: 'TICA',
      citationUrl: 'https://tica.org/ticas-breeds/browse-all-breeds/#british-longhair',
      referenceNotes: 'Official TICA standard: teddy-bear appearance, plush semi-long coat.',
    },
  },
  {
    id: 'burmese',
    displayName: 'Burmese',
    category: 'domestic',
    gameRarity: 'uncommon',
    eligibleDiscoveryLocations: ['home_neighborhood', 'park'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'park'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'solid',
      bodyBuild: 'compact',
      earType: 'rounded',
      tailType: 'full',
      primaryColor: 'warm_sable_brown',
      eyeColor: 'gold',
    },
    portraitAssetKey: 'art_needed:portrait:burmese',
    bodyAssetKey: 'art_needed:body:burmese',
    animationAssetKeys: ['art_needed:anim:burmese:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Surprisingly heavy "brick wrapped in silk" body build.',
    description: 'An affectionate, social breed with silky dark sable coat and surprising heft.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/burmese/',
      referenceNotes: 'Official CFA standard: compact heavy body, satin sable coat, expressive eyes.',
    },
  },
  {
    id: 'chartreux',
    displayName: 'Chartreux',
    category: 'domestic',
    gameRarity: 'uncommon',
    eligibleDiscoveryLocations: ['shop_district', 'home_neighborhood'],
    eligibleDiscoveryConditions: { locationIds: ['shop_district', 'home_neighborhood'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'solid',
      bodyBuild: 'muscular',
      earType: 'straight',
      tailType: 'full',
      primaryColor: 'slate_blue',
      eyeColor: 'bright_orange',
    },
    portraitAssetKey: 'art_needed:portrait:chartreux',
    bodyAssetKey: 'art_needed:body:chartreux',
    animationAssetKeys: ['art_needed:anim:chartreux:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Famous French domestic cat known as the "smiling cat".',
    description: 'A quiet, muscular French blue cat with water-resistant woolly coat and smiling head structure.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/chartreux/',
      referenceNotes: 'Official CFA standard: double coat slate blue, copper to gold eyes.',
    },
  },
  {
    id: 'cornish_rex',
    displayName: 'Cornish Rex',
    category: 'domestic',
    gameRarity: 'rare_domestic',
    eligibleDiscoveryLocations: ['park', 'shop_district'],
    eligibleDiscoveryConditions: { locationIds: ['park', 'shop_district'], timeOfDay: 'day' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'tabby',
      bodyBuild: 'slender',
      earType: 'large_pointed',
      tailType: 'full',
      primaryColor: 'cinnamon',
      eyeColor: 'hazel',
    },
    portraitAssetKey: 'art_needed:portrait:cornish_rex',
    bodyAssetKey: 'art_needed:body:cornish_rex',
    animationAssetKeys: ['art_needed:anim:cornish_rex:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Curled marcel waves in coat and greyhound-like arched back.',
    description: 'An energetic, slender breed with soft Marcel-waved short fur and large expressive ears.',
    provenance: {
      sourceOrganization: 'TICA',
      citationUrl: 'https://tica.org/ticas-breeds/browse-all-breeds/#cornish-rex',
      referenceNotes: 'Official TICA standard: egg-shaped head, Marcel waves, whipped tail.',
    },
  },
  {
    id: 'devon_rex',
    displayName: 'Devon Rex',
    category: 'domestic',
    gameRarity: 'rare_domestic',
    eligibleDiscoveryLocations: ['home_neighborhood', 'cafe'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'cafe'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'bicolor',
      bodyBuild: 'slender',
      earType: 'large_pointed',
      tailType: 'full',
      primaryColor: 'cream',
      secondaryColor: 'chocolate',
      eyeColor: 'green_gold',
    },
    portraitAssetKey: 'art_needed:portrait:devon_rex',
    bodyAssetKey: 'art_needed:body:devon_rex',
    animationAssetKeys: ['art_needed:anim:devon_rex:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Pixie-faced cat with huge ears sitting on high perches indoors.',
    description: 'An elf-like domestic cat with oversized ears, short wavy coat, and mischievous charm.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/devon-rex/',
      referenceNotes: 'Official CFA standard: low set ears, short wavy coat, impish face.',
    },
  },
  {
    id: 'egyptian_mau',
    displayName: 'Egyptian Mau',
    category: 'domestic',
    gameRarity: 'rare_domestic',
    eligibleDiscoveryLocations: ['park', 'wild_fringe'],
    eligibleDiscoveryConditions: { locationIds: ['park', 'wild_fringe'], timeOfDay: 'day' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'spotted',
      bodyBuild: 'muscular',
      earType: 'straight',
      tailType: 'full',
      primaryColor: 'silver',
      secondaryColor: 'dark_spots',
      eyeColor: 'gooseberry_green',
    },
    portraitAssetKey: 'art_needed:portrait:egyptian_mau',
    bodyAssetKey: 'art_needed:body:egyptian_mau',
    animationAssetKeys: ['art_needed:anim:egyptian_mau:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Fast runner with natural spots and a worry mark on forehead.',
    description: 'The only naturally spotted domestic cat breed, capable of impressive sprints.',
    provenance: {
      sourceOrganization: 'TICA',
      citationUrl: 'https://tica.org/ticas-breeds/browse-all-breeds/#egyptian-mau',
      referenceNotes: 'Official TICA standard: naturally occurring spotted coat, gooseberry green eyes.',
    },
  },
  {
    id: 'exotic_shorthair',
    displayName: 'Exotic Shorthair',
    category: 'domestic',
    gameRarity: 'common',
    eligibleDiscoveryLocations: ['home_neighborhood', 'cafe'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'cafe'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'solid',
      bodyBuild: 'cobbly',
      earType: 'straight',
      tailType: 'full',
      primaryColor: 'cream_white',
      eyeColor: 'copper',
    },
    portraitAssetKey: 'art_needed:portrait:exotic_shorthair',
    bodyAssetKey: 'art_needed:body:exotic_shorthair',
    animationAssetKeys: ['art_needed:anim:exotic_shorthair:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Looks like a teddy bear Persian in a plush short coat.',
    description: 'A sweet, quiet breed with the flat face of a Persian and plush short fur.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/exotic/',
      referenceNotes: 'Official CFA standard: cobby body, round skull, dense plush coat.',
    },
  },
  {
    id: 'havana_brown',
    displayName: 'Havana Brown',
    category: 'domestic',
    gameRarity: 'rare_domestic',
    eligibleDiscoveryLocations: ['shop_district', 'home_neighborhood'],
    eligibleDiscoveryConditions: { locationIds: ['shop_district', 'home_neighborhood'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'solid',
      bodyBuild: 'medium',
      earType: 'straight',
      tailType: 'full',
      primaryColor: 'mahogany_brown',
      eyeColor: 'vivid_green',
    },
    portraitAssetKey: 'art_needed:portrait:havana_brown',
    bodyAssetKey: 'art_needed:body:havana_brown',
    animationAssetKeys: ['art_needed:anim:havana_brown:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Warm chocolate mahogany coat with striking green eyes.',
    description: 'A rare domestic cat breed defined by rich warm mahogany fur and expressive green eyes.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/havana-brown/',
      referenceNotes: 'Official CFA standard: warm chocolate mahogany, emerald eyes, corn-cob muzzle.',
    },
  },
  {
    id: 'japanese_bobtail',
    displayName: 'Japanese Bobtail',
    category: 'domestic',
    gameRarity: 'uncommon',
    eligibleDiscoveryLocations: ['home_neighborhood', 'shop_district', 'cafe'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'shop_district', 'cafe'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'calico',
      bodyBuild: 'slender',
      earType: 'straight',
      tailType: 'bobbed',
      primaryColor: 'white',
      secondaryColor: 'red_black_patches',
      eyeColor: 'gold_or_odd',
    },
    portraitAssetKey: 'calico', // Batch seed match
    bodyAssetKey: 'calico',
    animationAssetKeys: ['calico:walk', 'calico:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Distinctive rabbit-like pom bobtail tail and lucky greeting pose.',
    description: 'An ancient Asian breed featuring a unique pom-like bobbed tail and energetic nature.',
    provenance: {
      sourceOrganization: 'TICA',
      citationUrl: 'https://tica.org/ticas-breeds/browse-all-breeds/#japanese-bobtail',
      referenceNotes: 'Official TICA standard: pom tail, high cheekbones, tricolor calico popularity.',
    },
  },
  {
    id: 'korat',
    displayName: 'Korat',
    category: 'domestic',
    gameRarity: 'uncommon',
    eligibleDiscoveryLocations: ['home_neighborhood', 'park'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'park'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'solid',
      bodyBuild: 'compact',
      earType: 'straight',
      tailType: 'full',
      primaryColor: 'silver_blue',
      eyeColor: 'luminous_green',
    },
    portraitAssetKey: 'art_needed:portrait:korat',
    bodyAssetKey: 'art_needed:body:korat',
    animationAssetKeys: ['art_needed:anim:korat:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Heart-shaped head structure with silver tipped blue fur.',
    description: 'A traditional Thai good-luck cat with silver-tipped blue coat and heart-shaped face.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/korat/',
      referenceNotes: 'Official CFA standard: heart head, silver tipped blue hair, luminous green eyes.',
    },
  },
  {
    id: 'laperm',
    displayName: 'LaPerm',
    category: 'domestic',
    gameRarity: 'uncommon',
    eligibleDiscoveryLocations: ['park', 'cafe'],
    eligibleDiscoveryConditions: { locationIds: ['park', 'cafe'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'medium',
      coatPattern: 'tabby',
      bodyBuild: 'medium',
      earType: 'straight',
      tailType: 'plumed',
      primaryColor: 'warm_amber',
      secondaryColor: 'dark_stripes',
      eyeColor: 'gold',
    },
    portraitAssetKey: 'art_needed:portrait:laperm',
    bodyAssetKey: 'art_needed:body:laperm',
    animationAssetKeys: ['art_needed:anim:laperm:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Loose ringlets and curls across the entire coat.',
    description: 'A gentle curly-coated domestic cat originating from an Oregon farm mutation.',
    provenance: {
      sourceOrganization: 'TICA',
      citationUrl: 'https://tica.org/ticas-breeds/browse-all-breeds/#laperm',
      referenceNotes: 'Official TICA standard: curly plush ringlet coat, gentle temperament.',
    },
  },
  {
    id: 'maine_coon',
    displayName: 'Maine Coon',
    category: 'domestic',
    gameRarity: 'common',
    eligibleDiscoveryLocations: ['home_neighborhood', 'park', 'wild_fringe'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'park', 'wild_fringe'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'long',
      coatPattern: 'tabby',
      bodyBuild: 'muscular',
      earType: 'tufted',
      tailType: 'plumed',
      primaryColor: 'brown_tabby',
      secondaryColor: 'white_chest',
      eyeColor: 'amber_green',
    },
    portraitAssetKey: 'art_needed:portrait:maine_coon',
    bodyAssetKey: 'art_needed:body:maine_coon',
    animationAssetKeys: ['art_needed:anim:maine_coon:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Gentle giant with Lynx-like ear tufts and massive bushy tail.',
    description: 'A large native North American domestic cat known for intelligence and gentle giant personality.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/maine-coon-cat/',
      referenceNotes: 'Official CFA standard: large tufted ears, rugged coat, bushy tail.',
    },
  },
  {
    id: 'manx',
    displayName: 'Manx',
    category: 'domestic',
    gameRarity: 'uncommon',
    eligibleDiscoveryLocations: ['home_neighborhood', 'park'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'park'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'tortoiseshell',
      bodyBuild: 'cobbly',
      earType: 'straight',
      tailType: 'bobbed',
      primaryColor: 'orange_black_blend',
      eyeColor: 'copper',
    },
    portraitAssetKey: 'tortoiseshell', // Batch seed match
    bodyAssetKey: 'tortoiseshell',
    animationAssetKeys: ['tortoiseshell:walk', 'tortoiseshell:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Tailless or rumpy bobbed tail cat with longer hind legs.',
    description: 'A round-shaped cat from the Isle of Man famous for natural tail mutation.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/manx/',
      referenceNotes: 'Official CFA standard: taillessness rumpy, high hindquarters, double coat.',
    },
  },
  {
    id: 'munchkin',
    displayName: 'Munchkin',
    category: 'domestic',
    gameRarity: 'uncommon',
    eligibleDiscoveryLocations: ['home_neighborhood', 'cafe', 'shop_district'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'cafe', 'shop_district'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'bicolor',
      bodyBuild: 'compact',
      earType: 'straight',
      tailType: 'full',
      primaryColor: 'orange',
      secondaryColor: 'white',
      eyeColor: 'amber',
    },
    portraitAssetKey: 'orange-tabby', // Batch seed match
    bodyAssetKey: 'orange-tabby',
    animationAssetKeys: ['orange-tabby:walk', 'orange-tabby:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Short legs with high energy and quick cornering abilities.',
    description: 'A playful domestic breed recognized by naturally shortened legs and sweet disposition.',
    provenance: {
      sourceOrganization: 'TICA',
      citationUrl: 'https://tica.org/ticas-breeds/browse-all-breeds/#munchkin',
      referenceNotes: 'Official TICA standard: short legs, medium spine, energetic stride.',
    },
  },
  {
    id: 'norwegian_forest_cat',
    displayName: 'Norwegian Forest Cat',
    category: 'domestic',
    gameRarity: 'uncommon',
    eligibleDiscoveryLocations: ['park', 'wild_fringe'],
    eligibleDiscoveryConditions: { locationIds: ['park', 'wild_fringe'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'long',
      coatPattern: 'tabby',
      bodyBuild: 'muscular',
      earType: 'tufted',
      tailType: 'plumed',
      primaryColor: 'silver_white',
      secondaryColor: 'black_tabby',
      eyeColor: 'green_gold',
    },
    portraitAssetKey: 'white-longhair', // Batch seed match
    bodyAssetKey: 'white-longhair',
    animationAssetKeys: ['white-longhair:walk', 'white-longhair:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Skilled climber with water-repellent double coat in wooded areas.',
    description: 'A rustic Scandinavian forest breed adapted to cold mountain climates.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/norwegian-forest-cat/',
      referenceNotes: 'Official CFA standard: triangular head, insulated water-repellent long coat.',
    },
  },
  {
    id: 'ocicat',
    displayName: 'Ocicat',
    category: 'domestic',
    gameRarity: 'rare_domestic',
    eligibleDiscoveryLocations: ['park', 'shop_district'],
    eligibleDiscoveryConditions: { locationIds: ['park', 'shop_district'], timeOfDay: 'day' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'spotted',
      bodyBuild: 'muscular',
      earType: 'straight',
      tailType: 'full',
      primaryColor: 'tawny_bronze',
      secondaryColor: 'dark_spots',
      eyeColor: 'amber',
    },
    portraitAssetKey: 'art_needed:portrait:ocicat',
    bodyAssetKey: 'art_needed:body:ocicat',
    animationAssetKeys: ['art_needed:anim:ocicat:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Wild ocelot look created purely from domestic breed origins.',
    description: 'An all-domestic cat breed bred to resemble a wild spotted ocelot without wild blood.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/ocicat/',
      referenceNotes: 'Official CFA standard: athletic spotted coat derived from Abyssinian/Siamese mixes.',
    },
  },
  {
    id: 'oriental_shorthair',
    displayName: 'Oriental Shorthair',
    category: 'domestic',
    gameRarity: 'uncommon',
    eligibleDiscoveryLocations: ['cafe', 'shop_district'],
    eligibleDiscoveryConditions: { locationIds: ['cafe', 'shop_district'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'solid',
      bodyBuild: 'slender',
      earType: 'large_pointed',
      tailType: 'full',
      primaryColor: 'ebony',
      eyeColor: 'vivid_green',
    },
    portraitAssetKey: 'art_needed:portrait:oriental_shorthair',
    bodyAssetKey: 'art_needed:body:oriental_shorthair',
    animationAssetKeys: ['art_needed:anim:oriental_shorthair:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Extreme svelte body with large flared ears and inquisitive stance.',
    description: 'A member of the Siamese family with over 300 coat color combinations.',
    provenance: {
      sourceOrganization: 'TICA',
      citationUrl: 'https://tica.org/ticas-breeds/browse-all-breeds/#oriental-shorthair',
      referenceNotes: 'Official TICA standard: wedge head, flared ears, fine boned svelte body.',
    },
  },
  {
    id: 'persian',
    displayName: 'Persian',
    category: 'domestic',
    gameRarity: 'common',
    eligibleDiscoveryLocations: ['home_neighborhood', 'cafe'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'cafe'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'long',
      coatPattern: 'solid',
      bodyBuild: 'cobbly',
      earType: 'straight',
      tailType: 'plumed',
      primaryColor: 'pure_white',
      eyeColor: 'copper_or_blue',
    },
    portraitAssetKey: 'white-longhair', // Batch seed match
    bodyAssetKey: 'white-longhair',
    animationAssetKeys: ['white-longhair:walk', 'white-longhair:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Luxurious long flowing coat and quiet sweet temperament.',
    description: 'One of the oldest domestic breeds, renowned for glitzy coat and dignified nature.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/persian/',
      referenceNotes: 'Official CFA standard: round head, short snub nose, abundant long coat.',
    },
  },
  {
    id: 'ragdoll',
    displayName: 'Ragdoll',
    category: 'domestic',
    gameRarity: 'common',
    eligibleDiscoveryLocations: ['home_neighborhood', 'cafe'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'cafe'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'long',
      coatPattern: 'colorpoint',
      bodyBuild: 'muscular',
      earType: 'straight',
      tailType: 'plumed',
      primaryColor: 'seal_point',
      secondaryColor: 'white_mittens',
      eyeColor: 'striking_blue',
    },
    portraitAssetKey: 'art_needed:portrait:ragdoll',
    bodyAssetKey: 'art_needed:body:ragdoll',
    animationAssetKeys: ['art_needed:anim:ragdoll:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Relaxes completely when held; friendly and puppy-like.',
    description: 'A large, affectionate cat known for going limp in contentment when petted.',
    provenance: {
      sourceOrganization: 'TICA',
      citationUrl: 'https://tica.org/ticas-breeds/browse-all-breeds/#ragdoll',
      referenceNotes: 'Official TICA standard: blue eyes, colorpoint coat, docile relaxed demeanor.',
    },
  },
  {
    id: 'russian_blue',
    displayName: 'Russian Blue',
    category: 'domestic',
    gameRarity: 'uncommon',
    eligibleDiscoveryLocations: ['home_neighborhood', 'shop_district'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'shop_district'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'solid',
      bodyBuild: 'slender',
      earType: 'straight',
      tailType: 'full',
      primaryColor: 'shimmering_blue_silver',
      eyeColor: 'vivid_emerald',
    },
    portraitAssetKey: 'art_needed:portrait:russian_blue',
    bodyAssetKey: 'art_needed:body:russian_blue',
    animationAssetKeys: ['art_needed:anim:russian_blue:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Silver tipped double coat and emerald eyes with a reserved demeanor.',
    description: 'An elegant silver-blue cat known for gentle devotion and plush double coat.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/russian-blue/',
      referenceNotes: 'Official CFA standard: bright green eyes, silver tipped blue coat, fine boning.',
    },
  },
  {
    id: 'scottish_fold',
    displayName: 'Scottish Fold',
    category: 'domestic',
    gameRarity: 'uncommon',
    eligibleDiscoveryLocations: ['home_neighborhood', 'cafe'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'cafe'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'tuxedo',
      bodyBuild: 'compact',
      earType: 'folded',
      tailType: 'full',
      primaryColor: 'black',
      secondaryColor: 'white',
      eyeColor: 'gold',
    },
    portraitAssetKey: 'tuxedo', // Batch seed match
    bodyAssetKey: 'tuxedo',
    animationAssetKeys: ['tuxedo:walk', 'tuxedo:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Folded ears forward giving an owl-like round head appearance.',
    description: 'A owl-faced cat breed with distinctive downward folded ears.',
    provenance: {
      sourceOrganization: 'TICA',
      citationUrl: 'https://tica.org/ticas-breeds/browse-all-breeds/#scottish-fold',
      referenceNotes: 'Official TICA standard: folded ear cap, large round eyes, sweet nature.',
    },
  },
  {
    id: 'selkirk_rex',
    displayName: 'Selkirk Rex',
    category: 'domestic',
    gameRarity: 'uncommon',
    eligibleDiscoveryLocations: ['shop_district', 'home_neighborhood'],
    eligibleDiscoveryConditions: { locationIds: ['shop_district', 'home_neighborhood'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'medium',
      coatPattern: 'solid',
      bodyBuild: 'cobbly',
      earType: 'straight',
      tailType: 'plumed',
      primaryColor: 'grey_smoke',
      eyeColor: 'hazel',
    },
    portraitAssetKey: 'art_needed:portrait:selkirk_rex',
    bodyAssetKey: 'art_needed:body:selkirk_rex',
    animationAssetKeys: ['art_needed:anim:selkirk_rex:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Teddy-bear look with soft curly whiskers and fleece coat.',
    description: 'A woolly-coated cat breed known as the "cat in sheep\'s clothing".',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/selkirk-rex/',
      referenceNotes: 'Official CFA standard: curly whiskers, woolly fleece texture, cobbly build.',
    },
  },
  {
    id: 'siamese',
    displayName: 'Siamese',
    category: 'domestic',
    gameRarity: 'common',
    eligibleDiscoveryLocations: ['home_neighborhood', 'shop_district', 'cafe'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'shop_district', 'cafe'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'colorpoint',
      bodyBuild: 'slender',
      earType: 'large_pointed',
      tailType: 'full',
      primaryColor: 'cream',
      secondaryColor: 'dark_seal_point',
      eyeColor: 'deep_blue',
    },
    portraitAssetKey: 'art_needed:portrait:siamese',
    bodyAssetKey: 'art_needed:body:siamese',
    animationAssetKeys: ['art_needed:anim:siamese:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Vocal chatterbox with sleek point coloration and sapphire eyes.',
    description: 'One of the iconic royal cats of Siam, renowned for intelligence and vocal charisma.',
    provenance: {
      sourceOrganization: 'TICA',
      citationUrl: 'https://tica.org/ticas-breeds/browse-all-breeds/#siamese',
      referenceNotes: 'Official TICA standard: long svelte lines, deep blue eyes, dark points.',
    },
  },
  {
    id: 'siberian',
    displayName: 'Siberian',
    category: 'domestic',
    gameRarity: 'uncommon',
    eligibleDiscoveryLocations: ['park', 'wild_fringe'],
    eligibleDiscoveryConditions: { locationIds: ['park', 'wild_fringe'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'long',
      coatPattern: 'tabby',
      bodyBuild: 'muscular',
      earType: 'tufted',
      tailType: 'plumed',
      primaryColor: 'golden_tabby',
      secondaryColor: 'white_throat',
      eyeColor: 'green_amber',
    },
    portraitAssetKey: 'art_needed:portrait:siberian',
    bodyAssetKey: 'art_needed:body:siberian',
    animationAssetKeys: ['art_needed:anim:siberian:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Heavy barrel chest and barrel-like agility in snowy or rainy weather.',
    description: 'An ancient Russian forest cat with a triple coat built for harsh winter survival.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/siberian/',
      referenceNotes: 'Official CFA standard: triple coat, barrel body shape, powerful jumping ability.',
    },
  },
  {
    id: 'singapura',
    displayName: 'Singapura',
    category: 'domestic',
    gameRarity: 'rare_domestic',
    eligibleDiscoveryLocations: ['shop_district', 'cafe'],
    eligibleDiscoveryConditions: { locationIds: ['shop_district', 'cafe'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'solid',
      bodyBuild: 'compact',
      earType: 'large_pointed',
      tailType: 'full',
      primaryColor: 'sepia_ivory',
      secondaryColor: 'ticked_dark_brown',
      eyeColor: 'large_hazel_green',
    },
    portraitAssetKey: 'art_needed:portrait:singapura',
    bodyAssetKey: 'art_needed:body:singapura',
    animationAssetKeys: ['art_needed:anim:singapura:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Smallest official domestic cat breed with huge eyes and sepia tick coat.',
    description: 'The smallest domestic cat breed, boasting large ears and sepia agouti ticking.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/singapura/',
      referenceNotes: 'Official CFA standard: smallest domestic breed, sepia agouti ticked coat.',
    },
  },
  {
    id: 'somali',
    displayName: 'Somali',
    category: 'domestic',
    gameRarity: 'uncommon',
    eligibleDiscoveryLocations: ['park', 'home_neighborhood'],
    eligibleDiscoveryConditions: { locationIds: ['park', 'home_neighborhood'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'long',
      coatPattern: 'solid',
      bodyBuild: 'slender',
      earType: 'large_pointed',
      tailType: 'plumed',
      primaryColor: 'ruddy_orange',
      secondaryColor: 'ticked_black',
      eyeColor: 'amber',
    },
    portraitAssetKey: 'art_needed:portrait:somali',
    bodyAssetKey: 'art_needed:body:somali',
    animationAssetKeys: ['art_needed:anim:somali:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Fox-like bushy tail and vibrant ticked coat in park gardens.',
    description: 'The long-haired counterpart to the Abyssinian, nicknamed the "Fox Cat".',
    provenance: {
      sourceOrganization: 'TICA',
      citationUrl: 'https://tica.org/ticas-breeds/browse-all-breeds/#somali',
      referenceNotes: 'Official TICA standard: long bushy tail, vibrant ticked coat, fox-like appearance.',
    },
  },
  {
    id: 'sphynx',
    displayName: 'Sphynx',
    category: 'domestic',
    gameRarity: 'rare_domestic',
    eligibleDiscoveryLocations: ['cafe', 'shop_district', 'home_neighborhood'],
    eligibleDiscoveryConditions: { locationIds: ['cafe', 'shop_district', 'home_neighborhood'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'hairless',
      coatPattern: 'solid',
      bodyBuild: 'medium',
      earType: 'large_pointed',
      tailType: 'full',
      primaryColor: 'pinkish_suede',
      eyeColor: 'lemon_green',
    },
    portraitAssetKey: 'art_needed:portrait:sphynx',
    bodyAssetKey: 'art_needed:body:sphynx',
    animationAssetKeys: ['art_needed:anim:sphynx:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Warm-bodied hairless cat seeking cozy indoor heat sources.',
    description: 'A hairless breed known for affectionate warmth, large ears, and suede-like skin.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/sphynx/',
      referenceNotes: 'Official CFA standard: peach fuzz hairlessness, lemon-shaped eyes, warm body.',
    },
  },
  {
    id: 'tonkinese',
    displayName: 'Tonkinese',
    category: 'domestic',
    gameRarity: 'uncommon',
    eligibleDiscoveryLocations: ['home_neighborhood', 'cafe'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'cafe'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'colorpoint',
      bodyBuild: 'medium',
      earType: 'straight',
      tailType: 'full',
      primaryColor: 'mink_platinum',
      secondaryColor: 'dark_mink_points',
      eyeColor: 'aqua',
    },
    portraitAssetKey: 'art_needed:portrait:tonkinese',
    bodyAssetKey: 'art_needed:body:tonkinese',
    animationAssetKeys: ['art_needed:anim:tonkinese:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Blend of Siamese points and Burmese mink tone with aqua eyes.',
    description: 'A cross of Siamese and Burmese breeds, prized for mink coat patterns and aqua eyes.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/tonkinese/',
      referenceNotes: 'Official CFA standard: mink pattern, aqua eyes, medium muscular frame.',
    },
  },
  {
    id: 'toyger',
    displayName: 'Toyger',
    category: 'domestic',
    gameRarity: 'rare_domestic',
    eligibleDiscoveryLocations: ['park', 'shop_district'],
    eligibleDiscoveryConditions: { locationIds: ['park', 'shop_district'], timeOfDay: 'day' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'tabby',
      bodyBuild: 'muscular',
      earType: 'straight',
      tailType: 'full',
      primaryColor: 'bright_orange',
      secondaryColor: 'bold_black_stripes',
      eyeColor: 'deep_gold',
    },
    portraitAssetKey: 'art_needed:portrait:toyger',
    bodyAssetKey: 'art_needed:body:toyger',
    animationAssetKeys: ['art_needed:anim:toyger:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Looks like a miniature tiger prowling park lawns.',
    description: 'Bred specifically to resemble a miniature wild tiger with bold vertical stripes.',
    provenance: {
      sourceOrganization: 'TICA',
      citationUrl: 'https://tica.org/ticas-breeds/browse-all-breeds/#toyger',
      referenceNotes: 'Official TICA standard: tiger striped pattern, athletic gait, domestic temperament.',
    },
  },
  {
    id: 'turkish_angora',
    displayName: 'Turkish Angora',
    category: 'domestic',
    gameRarity: 'uncommon',
    eligibleDiscoveryLocations: ['home_neighborhood', 'cafe'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'cafe'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'long',
      coatPattern: 'solid',
      bodyBuild: 'slender',
      earType: 'tufted',
      tailType: 'plumed',
      primaryColor: 'pure_shimmering_white',
      eyeColor: 'odd_blue_amber',
    },
    portraitAssetKey: 'white-longhair', // Batch seed match
    bodyAssetKey: 'white-longhair',
    animationAssetKeys: ['white-longhair:walk', 'white-longhair:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Silky fine longhair with elegant plumytail and ballerina posture.',
    description: 'An ancient natural Turkish breed admired for silky white coat and graceful spirit.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/turkish-angora/',
      referenceNotes: 'Official CFA standard: fine boned, silky long hair, plume tail.',
    },
  },
  {
    id: 'turkish_van',
    displayName: 'Turkish Van',
    category: 'domestic',
    gameRarity: 'rare_domestic',
    eligibleDiscoveryLocations: ['park', 'wild_fringe'],
    eligibleDiscoveryConditions: { locationIds: ['park', 'wild_fringe'], timeOfDay: 'day' },
    appearanceFlags: {
      coatLength: 'medium',
      coatPattern: 'bicolor',
      bodyBuild: 'muscular',
      earType: 'straight',
      tailType: 'plumed',
      primaryColor: 'cashmere_white',
      secondaryColor: 'auburn_head_tail',
      eyeColor: 'amber_or_blue',
    },
    portraitAssetKey: 'art_needed:portrait:turkish_van',
    bodyAssetKey: 'art_needed:body:turkish_van',
    animationAssetKeys: ['art_needed:anim:turkish_van:walk'],
    artStatus: 'art_needed',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'The "Swimming Cat" enjoying streams and ponds.',
    description: 'Famous Turkish cat breed with distinct color markings restricted to head and tail.',
    provenance: {
      sourceOrganization: 'CFA',
      citationUrl: 'https://cfa.org/turkish-van/',
      referenceNotes: 'Official CFA standard: Van pattern (head/tail color only), water-resistant coat.',
    },
  },
  {
    id: 'domestic_tabby_mix',
    displayName: 'Domestic Shorthair Mix',
    category: 'domestic',
    gameRarity: 'common',
    eligibleDiscoveryLocations: ['home_neighborhood', 'park', 'shop_district', 'cafe'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'park', 'shop_district', 'cafe'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'tabby',
      bodyBuild: 'medium',
      earType: 'straight',
      tailType: 'full',
      primaryColor: 'orange',
      secondaryColor: 'cream_stripes',
      eyeColor: 'gold',
    },
    portraitAssetKey: 'orange-tabby', // Batch seed match
    bodyAssetKey: 'orange-tabby',
    animationAssetKeys: ['orange-tabby:walk', 'orange-tabby:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Friendly neighborhood orange tabby exploring gardens.',
    description: 'Classic beloved domestic shorthair mix coat pattern.',
    provenance: {
      sourceOrganization: 'GameOriginal',
      referenceNotes: 'Domestic coat mix variant based on widespread household feline genetics.',
    },
  },
  {
    id: 'domestic_calico_mix',
    displayName: 'Domestic Calico Mix',
    category: 'domestic',
    gameRarity: 'common',
    eligibleDiscoveryLocations: ['home_neighborhood', 'park', 'cafe'],
    eligibleDiscoveryConditions: { locationIds: ['home_neighborhood', 'park', 'cafe'], timeOfDay: 'any' },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'calico',
      bodyBuild: 'medium',
      earType: 'straight',
      tailType: 'full',
      primaryColor: 'white',
      secondaryColor: 'orange_black_patches',
      eyeColor: 'green',
    },
    portraitAssetKey: 'calico', // Batch seed match
    bodyAssetKey: 'calico',
    animationAssetKeys: ['calico:walk', 'calico:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: true,
    ancestryEligibility: true,
    discoveryHints: 'Sweet patchwork coat cat sunbathing near porches.',
    description: 'Vibrant tricolor calico coat pattern on a friendly domestic cat.',
    provenance: {
      sourceOrganization: 'GameOriginal',
      referenceNotes: 'Domestic coat mix variant based on X-linked calico pigmentation.',
    },
  },
];

export const WILD_CATS_CATALOG: CatCatalogEntry[] = [
  {
    id: 'wild_caracal',
    displayName: 'Caracal',
    category: 'wild',
    gameRarity: 'wild',
    eligibleDiscoveryLocations: ['wild_fringe', 'deep_park_trail'],
    eligibleDiscoveryConditions: { locationIds: ['wild_fringe', 'deep_park_trail'], requiredBefriendLevel: 40 },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'solid',
      bodyBuild: 'wild_large',
      earType: 'tufted',
      tailType: 'full',
      primaryColor: 'reddish_sandy_tan',
      eyeColor: 'green_amber',
    },
    portraitAssetKey: 'caracal', // Batch seed match
    bodyAssetKey: 'caracal',
    animationAssetKeys: ['caracal:pounce', 'caracal:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: false,
    ancestryEligibility: false,
    discoveryHints: 'Long black ear tufts visible when resting high on rocky ledges.',
    description: 'A striking wild felid famous for extraordinary leaping skills and long black ear tufts.',
    provenance: {
      sourceOrganization: 'FelineTaxonomy',
      referenceNotes: 'Caracal caracal: wild species native to Africa and Southwest Asia.',
    },
  },
  {
    id: 'wild_serval',
    displayName: 'Serval',
    category: 'wild',
    gameRarity: 'wild',
    eligibleDiscoveryLocations: ['wild_fringe', 'deep_park_trail'],
    eligibleDiscoveryConditions: { locationIds: ['wild_fringe', 'deep_park_trail'], requiredBefriendLevel: 45 },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'spotted',
      bodyBuild: 'wild_large',
      earType: 'large_pointed',
      tailType: 'bobbed',
      primaryColor: 'golden_yellow',
      secondaryColor: 'bold_black_spots',
      eyeColor: 'amber',
    },
    portraitAssetKey: 'serval', // Batch seed match
    bodyAssetKey: 'serval',
    animationAssetKeys: ['serval:walk', 'serval:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: false,
    ancestryEligibility: false,
    discoveryHints: 'Remarkably long legs and oversized oval ears listening in tall grasses.',
    description: 'A slender wild cat with the longest legs relative to body size of any cat.',
    provenance: {
      sourceOrganization: 'FelineTaxonomy',
      referenceNotes: 'Leptailurus serval: wild cat of sub-Saharan grasslands.',
    },
  },
  {
    id: 'wild_eurasian_lynx',
    displayName: 'Eurasian Lynx',
    category: 'wild',
    gameRarity: 'wild',
    eligibleDiscoveryLocations: ['wild_fringe', 'mountain_overlook'],
    eligibleDiscoveryConditions: { locationIds: ['wild_fringe', 'mountain_overlook'], requiredBefriendLevel: 50 },
    appearanceFlags: {
      coatLength: 'medium',
      coatPattern: 'spotted',
      bodyBuild: 'wild_large',
      earType: 'tufted',
      tailType: 'bobbed',
      primaryColor: 'silver_reddish_brown',
      secondaryColor: 'dark_spots',
      eyeColor: 'pale_gold',
    },
    portraitAssetKey: 'eurasian-lynx', // Batch seed match
    bodyAssetKey: 'eurasian-lynx',
    animationAssetKeys: ['eurasian-lynx:walk', 'eurasian-lynx:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: false,
    ancestryEligibility: false,
    discoveryHints: 'Large padded paws and black ear tufts high on snowy ridges.',
    description: 'A powerful medium-sized wild cat built for cold forest terrain.',
    provenance: {
      sourceOrganization: 'FelineTaxonomy',
      referenceNotes: 'Lynx lynx: native wild cat species across European and Siberian forests.',
    },
  },
  {
    id: 'wild_sand_cat',
    displayName: 'Sand Cat',
    category: 'wild',
    gameRarity: 'wild',
    eligibleDiscoveryLocations: ['wild_fringe', 'dune_boundary'],
    eligibleDiscoveryConditions: { locationIds: ['wild_fringe', 'dune_boundary'], requiredBefriendLevel: 40 },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'solid',
      bodyBuild: 'wild_small',
      earType: 'large_pointed',
      tailType: 'full',
      primaryColor: 'sandy_buff',
      secondaryColor: 'faint_stripes',
      eyeColor: 'greenish_yellow',
    },
    portraitAssetKey: 'sand-cat', // Batch seed match
    bodyAssetKey: 'sand-cat',
    animationAssetKeys: ['sand-cat:walk', 'sand-cat:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: false,
    ancestryEligibility: false,
    discoveryHints: 'Dense fur padding underneath paws leaves barely any footprints in sand.',
    description: 'A desert specialist felid with broad flat head and padded paws.',
    provenance: {
      sourceOrganization: 'FelineTaxonomy',
      referenceNotes: 'Felis margarita: true desert-dwelling wild cat.',
    },
  },
  {
    id: 'wild_pallas_cat',
    displayName: 'Pallas\'s Cat',
    category: 'wild',
    gameRarity: 'wild',
    eligibleDiscoveryLocations: ['wild_fringe', 'mountain_overlook'],
    eligibleDiscoveryConditions: { locationIds: ['wild_fringe', 'mountain_overlook'], requiredBefriendLevel: 50 },
    appearanceFlags: {
      coatLength: 'long',
      coatPattern: 'solid',
      bodyBuild: 'wild_small',
      earType: 'rounded',
      tailType: 'plumed',
      primaryColor: 'frosty_grey',
      eyeColor: 'amber_yellow',
    },
    portraitAssetKey: 'pallas-cat', // Batch seed match
    bodyAssetKey: 'pallas-cat',
    animationAssetKeys: ['pallas-cat:walk', 'pallas-cat:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: false,
    ancestryEligibility: false,
    discoveryHints: 'Ultra-fluffy round body crouching low behind rocks.',
    description: 'Also known as the Manul, famous for expressive round eyes and dense winter fluff.',
    provenance: {
      sourceOrganization: 'FelineTaxonomy',
      referenceNotes: 'Otocolobus manul: montane wild cat of Central Asia.',
    },
  },
  {
    id: 'wild_rusty_spotted_cat',
    displayName: 'Rusty-Spotted Cat',
    category: 'wild',
    gameRarity: 'wild',
    eligibleDiscoveryLocations: ['wild_fringe', 'deep_park_trail'],
    eligibleDiscoveryConditions: { locationIds: ['wild_fringe', 'deep_park_trail'], requiredBefriendLevel: 35 },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'spotted',
      bodyBuild: 'wild_small',
      earType: 'rounded',
      tailType: 'full',
      primaryColor: 'greyish_fawn',
      secondaryColor: 'rusty_red_spots',
      eyeColor: 'honey_gold',
    },
    portraitAssetKey: 'rusty-spotted-cat', // Batch seed match
    bodyAssetKey: 'rusty-spotted-cat',
    animationAssetKeys: ['rusty-spotted-cat:walk', 'rusty-spotted-cat:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: false,
    ancestryEligibility: false,
    discoveryHints: 'Tiny wild cat timidly peering through dense bamboo or underbrush.',
    description: 'One of the smallest wild feline species on earth, agile and quick.',
    provenance: {
      sourceOrganization: 'FelineTaxonomy',
      referenceNotes: 'Prionailurus rubiginosus: miniature wild cat species.',
    },
  },
  {
    id: 'wild_snow_leopard',
    displayName: 'Snow Leopard',
    category: 'wild',
    gameRarity: 'wild',
    eligibleDiscoveryLocations: ['mountain_overlook'],
    eligibleDiscoveryConditions: { locationIds: ['mountain_overlook'], requiredBefriendLevel: 60, weatherCondition: 'foggy' },
    appearanceFlags: {
      coatLength: 'long',
      coatPattern: 'rosette',
      bodyBuild: 'wild_large',
      earType: 'rounded',
      tailType: 'plumed',
      primaryColor: 'smoky_grey_white',
      secondaryColor: 'dark_rosettes',
      eyeColor: 'pale_grey_blue',
    },
    portraitAssetKey: 'snow-leopard', // Batch seed match
    bodyAssetKey: 'snow-leopard',
    animationAssetKeys: ['snow-leopard:walk', 'snow-leopard:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: false,
    ancestryEligibility: false,
    discoveryHints: 'An elusive phantom of the snows appearing during mist high on the peak.',
    description: 'The majestic ghost of the mountains, featuring a massive fur tail for balance.',
    provenance: {
      sourceOrganization: 'FelineTaxonomy',
      referenceNotes: 'Panthera uncia: high altitude wild mountain felid.',
    },
  },
  {
    id: 'wild_clouded_leopard',
    displayName: 'Clouded Leopard',
    category: 'wild',
    gameRarity: 'wild',
    eligibleDiscoveryLocations: ['wild_fringe', 'deep_park_trail'],
    eligibleDiscoveryConditions: { locationIds: ['wild_fringe', 'deep_park_trail'], requiredBefriendLevel: 55 },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'rosette',
      bodyBuild: 'wild_large',
      earType: 'rounded',
      tailType: 'full',
      primaryColor: 'golden_tan',
      secondaryColor: 'clouded_blotches',
      eyeColor: 'greenish_amber',
    },
    portraitAssetKey: 'clouded-leopard', // Batch seed match
    bodyAssetKey: 'clouded-leopard',
    animationAssetKeys: ['clouded-leopard:walk', 'clouded-leopard:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: false,
    ancestryEligibility: false,
    discoveryHints: 'Master tree climber lingering on ancient thick forest branches.',
    description: 'An arboreal wild cat with large cloud-like blotches and impressive climbing agility.',
    provenance: {
      sourceOrganization: 'FelineTaxonomy',
      referenceNotes: 'Neofelis nebulosa: rainforest and woodland felid.',
    },
  },
];

export const FANTASY_CATS_CATALOG: CatCatalogEntry[] = [
  {
    id: 'fantasy_moon',
    displayName: 'Moon Cat',
    category: 'fantasy',
    gameRarity: 'fantasy',
    eligibleDiscoveryLocations: ['mountain_overlook', 'park'],
    eligibleDiscoveryConditions: { locationIds: ['mountain_overlook', 'park'], timeOfDay: 'night', weatherCondition: 'starlight', requiredBefriendLevel: 50 },
    appearanceFlags: {
      coatLength: 'medium',
      coatPattern: 'mystic_glow',
      bodyBuild: 'ethereal',
      earType: 'tufted',
      tailType: 'ethereal_whisps',
      primaryColor: 'midnight_silver',
      secondaryColor: 'lunar_crescent_shimmer',
      eyeColor: 'silver_moonlight',
    },
    portraitAssetKey: 'moon', // Batch seed match
    bodyAssetKey: 'moon',
    animationAssetKeys: ['moon:float', 'moon:glow'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: false,
    ancestryEligibility: false,
    discoveryHints: 'Appears under clear midnight moonlight near peaceful reflections.',
    description: 'A legendary mystical feline woven from silver moonlight and quiet celestial night.',
    provenance: {
      sourceOrganization: 'GameOriginal',
      referenceNotes: 'Original fantasy creation for Cats game rare encounters.',
    },
  },
  {
    id: 'fantasy_starlight',
    displayName: 'Starlight Cat',
    category: 'fantasy',
    gameRarity: 'fantasy',
    eligibleDiscoveryLocations: ['mountain_overlook', 'deep_park_trail'],
    eligibleDiscoveryConditions: { locationIds: ['mountain_overlook', 'deep_park_trail'], timeOfDay: 'night', weatherCondition: 'starlight', requiredBefriendLevel: 50 },
    appearanceFlags: {
      coatLength: 'medium',
      coatPattern: 'mystic_glow',
      bodyBuild: 'ethereal',
      earType: 'straight',
      tailType: 'ethereal_whisps',
      primaryColor: 'deep_indigo',
      secondaryColor: 'twinkling_stardust',
      eyeColor: 'sparkling_violet',
    },
    portraitAssetKey: 'starlight', // Batch seed match
    bodyAssetKey: 'starlight',
    animationAssetKeys: ['starlight:sparkle', 'starlight:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: false,
    ancestryEligibility: false,
    discoveryHints: 'Follows starlight constellations when night skies are bright and clear.',
    description: 'An ethereal companion feline with coat shimmering like distant stellar nebulae.',
    provenance: {
      sourceOrganization: 'GameOriginal',
      referenceNotes: 'Original fantasy creation for Cats game rare encounters.',
    },
  },
  {
    id: 'fantasy_cloud',
    displayName: 'Cloud Cat',
    category: 'fantasy',
    gameRarity: 'fantasy',
    eligibleDiscoveryLocations: ['mountain_overlook', 'park'],
    eligibleDiscoveryConditions: { locationIds: ['mountain_overlook', 'park'], weatherCondition: 'foggy', requiredBefriendLevel: 45 },
    appearanceFlags: {
      coatLength: 'long',
      coatPattern: 'mystic_glow',
      bodyBuild: 'ethereal',
      earType: 'rounded',
      tailType: 'plumed',
      primaryColor: 'soft_cumulus_white',
      secondaryColor: 'sky_blue_tint',
      eyeColor: 'misty_grey',
    },
    portraitAssetKey: 'cloud', // Batch seed match
    bodyAssetKey: 'cloud',
    animationAssetKeys: ['cloud:float', 'cloud:drift'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: false,
    ancestryEligibility: false,
    discoveryHints: 'Drifts gently down with rolling morning fog on high terrain.',
    description: 'A soft cloud-form feline that floats lightly without disturbing a single blade of grass.',
    provenance: {
      sourceOrganization: 'GameOriginal',
      referenceNotes: 'Original fantasy creation for Cats game rare encounters.',
    },
  },
  {
    id: 'fantasy_forest',
    displayName: 'Forest Spirit Cat',
    category: 'fantasy',
    gameRarity: 'fantasy',
    eligibleDiscoveryLocations: ['deep_park_trail', 'wild_fringe'],
    eligibleDiscoveryConditions: { locationIds: ['deep_park_trail', 'wild_fringe'], timeOfDay: 'dusk', requiredBefriendLevel: 50 },
    appearanceFlags: {
      coatLength: 'medium',
      coatPattern: 'mystic_glow',
      bodyBuild: 'ethereal',
      earType: 'tufted',
      tailType: 'plumed',
      primaryColor: 'moss_emerald',
      secondaryColor: 'golden_pollen_glow',
      eyeColor: 'deep_woodland_green',
    },
    portraitAssetKey: 'forest', // Batch seed match
    bodyAssetKey: 'forest',
    animationAssetKeys: ['forest:sprout', 'forest:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: false,
    ancestryEligibility: false,
    discoveryHints: 'Leaves glowing botanical footprints near ancient mossy tree roots.',
    description: 'An ancient woodland guardian cat adorned with delicate glowing leaf tendrils.',
    provenance: {
      sourceOrganization: 'GameOriginal',
      referenceNotes: 'Original fantasy creation for Cats game rare encounters.',
    },
  },
  {
    id: 'fantasy_crystal',
    displayName: 'Crystal Cat',
    category: 'fantasy',
    gameRarity: 'fantasy',
    eligibleDiscoveryLocations: ['dune_boundary', 'mountain_overlook'],
    eligibleDiscoveryConditions: { locationIds: ['dune_boundary', 'mountain_overlook'], timeOfDay: 'day', requiredBefriendLevel: 55 },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'mystic_glow',
      bodyBuild: 'compact',
      earType: 'straight',
      tailType: 'full',
      primaryColor: 'translucent_quartz',
      secondaryColor: 'prismatic_shimmer',
      eyeColor: 'crystalline_cyan',
    },
    portraitAssetKey: 'crystal', // Batch seed match
    bodyAssetKey: 'crystal',
    animationAssetKeys: ['crystal:refract', 'crystal:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: false,
    ancestryEligibility: false,
    discoveryHints: 'Refracts sunlight into vivid rainbows along rocky mineral surfaces.',
    description: 'A radiant prism cat carved from crystalline light and sparkling quartz.',
    provenance: {
      sourceOrganization: 'GameOriginal',
      referenceNotes: 'Original fantasy creation for Cats game rare encounters.',
    },
  },
  {
    id: 'fantasy_ember',
    displayName: 'Ember Cat',
    category: 'fantasy',
    gameRarity: 'fantasy',
    eligibleDiscoveryLocations: ['wild_fringe', 'mountain_overlook'],
    eligibleDiscoveryConditions: { locationIds: ['wild_fringe', 'mountain_overlook'], timeOfDay: 'dusk', requiredBefriendLevel: 55 },
    appearanceFlags: {
      coatLength: 'short',
      coatPattern: 'mystic_glow',
      bodyBuild: 'slender',
      earType: 'large_pointed',
      tailType: 'ethereal_whisps',
      primaryColor: 'charcoal_black',
      secondaryColor: 'warm_ember_glow',
      eyeColor: 'flame_orange',
    },
    portraitAssetKey: 'ember', // Batch seed match
    bodyAssetKey: 'ember',
    animationAssetKeys: ['ember:flicker', 'ember:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: false,
    ancestryEligibility: false,
    discoveryHints: 'Warm cozy glowing sparks dance around its coat during twilight.',
    description: 'A comforting hearth spirit cat carrying the gentle flicker of warm campfire embers.',
    provenance: {
      sourceOrganization: 'GameOriginal',
      referenceNotes: 'Original fantasy creation for Cats game rare encounters.',
    },
  },
  {
    id: 'fantasy_aurora',
    displayName: 'Aurora Cat',
    category: 'fantasy',
    gameRarity: 'fantasy',
    eligibleDiscoveryLocations: ['mountain_overlook'],
    eligibleDiscoveryConditions: { locationIds: ['mountain_overlook'], timeOfDay: 'night', weatherCondition: 'starlight', requiredBefriendLevel: 60 },
    appearanceFlags: {
      coatLength: 'long',
      coatPattern: 'mystic_glow',
      bodyBuild: 'ethereal',
      earType: 'tufted',
      tailType: 'plumed',
      primaryColor: 'aurora_magenta',
      secondaryColor: 'northern_green_wave',
      eyeColor: 'iridescent_cyan',
    },
    portraitAssetKey: 'aurora', // Batch seed match
    bodyAssetKey: 'aurora',
    animationAssetKeys: ['aurora:wave', 'aurora:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: false,
    ancestryEligibility: false,
    discoveryHints: 'Dances high above the clouds when polar northern lights shimmer.',
    description: 'A breathtaking celestial felid embodying the shifting colors of northern lights.',
    provenance: {
      sourceOrganization: 'GameOriginal',
      referenceNotes: 'Original fantasy creation for Cats game rare encounters.',
    },
  },
  {
    id: 'fantasy_blossom',
    displayName: 'Blossom Cat',
    category: 'fantasy',
    gameRarity: 'fantasy',
    eligibleDiscoveryLocations: ['park', 'cafe'],
    eligibleDiscoveryConditions: { locationIds: ['park', 'cafe'], timeOfDay: 'day', requiredBefriendLevel: 45 },
    appearanceFlags: {
      coatLength: 'medium',
      coatPattern: 'mystic_glow',
      bodyBuild: 'slender',
      earType: 'straight',
      tailType: 'plumed',
      primaryColor: 'sakura_pink',
      secondaryColor: 'petal_white_accents',
      eyeColor: 'spring_green',
    },
    portraitAssetKey: 'blossom', // Batch seed match
    bodyAssetKey: 'blossom',
    animationAssetKeys: ['blossom:petal_fall', 'blossom:idle'],
    artStatus: 'batch_seed_ready',
    creatorAllowed: false,
    ancestryEligibility: false,
    discoveryHints: 'Resting quietly beneath blooming spring trees in full flower.',
    description: 'A cheerful botanical feline accompanied by a gentle trail of floating flower petals.',
    provenance: {
      sourceOrganization: 'GameOriginal',
      referenceNotes: 'Original fantasy creation for Cats game rare encounters.',
    },
  },
];

export const ALL_CAT_CATALOG: CatCatalogEntry[] = [
  ...DOMESTIC_BREEDS_CATALOG,
  ...WILD_CATS_CATALOG,
  ...FANTASY_CATS_CATALOG,
];

export function getCatalogSummary(): CatalogSummary {
  const domestic = ALL_CAT_CATALOG.filter((c) => c.category === 'domestic');
  const wild = ALL_CAT_CATALOG.filter((c) => c.category === 'wild');
  const fantasy = ALL_CAT_CATALOG.filter((c) => c.category === 'fantasy');

  return {
    totalDomesticBreeds: domestic.length,
    totalDomesticCoatVariants: domestic.filter((c) => c.id.includes('mix')).length,
    totalWildTypes: wild.length,
    totalFantasyForms: fantasy.length,
    batchSeedCount: ALL_CAT_CATALOG.filter((c) => c.artStatus === 'batch_seed_ready').length,
    artNeededCount: ALL_CAT_CATALOG.filter((c) => c.artStatus === 'art_needed').length,
  };
}

export function findCatalogEntry(id: string): CatCatalogEntry | undefined {
  return ALL_CAT_CATALOG.find((c) => c.id === id);
}
